export const englishLanguage = {
  "schedulerMaintenance": "Scheduler Maintenance",
  "max": "Max",
  "min": "Min",
  "tolerance": "Tolerance",
  "actualValue": "Actual Value",
  "actionsOnFailure": "Actions on Failure",
  "monitoringFrequency": "Monitoring Frequency",
  "expectedValue": "Expected Value",
  "qcId": "QC ID",
  "expectedValueRange": "Expected Value Range",
  "dataPointID": "Data Point ID",
  "pressure": "Pressure",
  "duration": "Duration",
  "rpm": "RPM",
  "workCenterId": "Work Center ID",
  "resourceId": "Resource ID",
  "adjustments": "Adjustments",
  "qualityControlParameters": "Quality Control Parameters",
  "resources": "Resources",
  "tools": "Tools",
  "safetyProcedures": "Safety Procedures",
  "yieldWasteTracking": "Yield & Waste Tracking",
  "triggerPoints": "Trigger Points",
  "packagingLabeling": "Packaging Labeling",
  "ccp": "CCP",
  "stepName": "Step Name",
  "instruction": "Instruction",
  "steps": "Steps",
  "id": "Id",
  "associatedStep": "Associated",
  "expectedCycleTime": "Expected Cycle Time",
  "ingredients": "Ingredients",
  "phases": "Phases",
  "phase": "Phase",
  "phaseId": "Phase ID",
  "phaseName": "Phase Name",
  "phasesName": "Phase Name",
  "inactive": "Inactive",
  "recipeId": "Recipe ID",
  "batchSize": "Batch Size",
  "batchUom": "Batch UOM",
  "totalExpectedCycleTime": "Total Expected Cycle Time",
  "totalActualCycleTime": "Total Actual Cycle Time",
  "active": "Active",
  "recipeStepDetails": "Recipe Step Details",
  "workInstructions": "Work Instructions",
  "dataCollections": "Data Collections",
  "parameterLists": "Parameter Lists",
  "classification": "Classification",
  "relaxedRecipeFlow": "Relaxed Flow Recipe",
  "scan": "Scan",
  "shipmentOrderNumber": "Shipment Order No",
  "dispatchDetails": "Dispatch Details",
  "dispatchDateTime": "Dispatch Date & Time",
  "recipientInfo": "Recipient Info",
  "dispatchInfo": "Dispatch Info",
  "recipeSteps": "Phase Steps",
  "recipeType": "Recipe Type",
  "recipe": "Recipe",
  "recipeName": "Recipe",
  "stageType": "Stage Type",
  stage: "Stage",
  "processOrderRelease": "Process Order Release",
  releaseProcessOrder: "Release Process Order",
  processOrder: "Process Order",
  appTitle: "Item Maintenance",
  count: "Count",
  shiftName: "Shift Name",
  description: "Description",
  entityType: "Entity Type",
  entityName: "Entity Name",
  item: "Item",
  searchActivities: "Search Activities",
  logout: "Logout",
  cancel: "Cancel",
  revision: "Revision",
  status: "Status",
  "qtyConsumed": "Qty Consumed",
  procurementType: "Procurement Type",
  lotSize: "Lot Size",
  createShift: "Create Shift",
  workCenter: "Work Center",
  resource: "Resource",
  add: "Add",
  save: "Save",
  main: "Main",
  alternateComponent: "Alternate Component",
  printDocument: "Print Document",
  customData: "Custom Data",
  itemGroup: "Item Group",
  qtyRestriction: "Qty Restriction",
  router: "Router",
  routing: "Routing",
  routingVersion: "Router Version",
  bom: "BOM",
  bomVersion: "BOM Version",
  assemblyDataType: "Asssembly Datatype",
  removalDataType: "Removal DataType",
  receiptDataType: "Receipt Datatype",
  currentVersion: "Current Version",
  itemType: "Item Type",
  create: "Create",
  "sequence": "Sequence",
  "version": "Version",
  "parentMaterial": "Parent Material",
  "validFrom": "Valid From",
  "validTo": "Valid To",
  versions: "Version: ",
  createdDate: "Created Date: ",
  modifiedTime: "Modified Date: ",
  availableDocuments: "Available Documents",
  assignedDocuments: "Assigned Documents",
  document: "Document",
  createItem: "Create Item",
  value: "Value",
  go: "GO",
  copy: "Copy",
  confirmCopy: "Confirm Copy",
  delete: "Delete",
  deleteMessage: "Are you sure you want to delete this item",
  insert: "Insert",
  removeSelected: "Remove Selected",
  removeAll: "Remove All",
  remove: "Remove",
  confirm: "Confirm",
  confirmDelete: "Confirm Delete",
  "boxNumber": "Box Number",
  "boxCapacity": "Box Capacity",
  "packetId": "Packet ID",
  "packetDescription": "Packet Description",
  "remainingCapacity": "Remaining Capacity",
  "totalPacketsInBox": "Total Packets in Box",
  "prelautid": "Material Id",
  "materialName": "Material Name",
  "uom": "UOM",
  "expectedQty": "Expected Qty",
  "unit": "Unit",
  "receivedQty": "Received Qty",
  "actions": "Actions",

  // ========================================= REASON CODE ===================================
  reasonCodeAppTitle: "Reason Code Maintenance",
  reasonCode: "Reason Code",
  category: "Category",
  messageType: "Message Type",
  createReasonCode: "Create Reason Code",
  rowSelectionMsg: "Do you want to continue with the row selection?",
  selectReasonCode: "Select Reason Code",

  // ========================================= REASON CODE ===================================
  routingTitle: "Routing Maintenance",
  "routingType": "Routing Type",
  routingSteps: "Routing Steps",

  subType: "Sub Type",
  dispositionGroup: "Disposition Group",

  relaxedRoutingFlow: "Relaxed Flow Routing",
  replicationToErp: "Replication To ERP",
  details: "Details",
  nextStepId: "Next Step Id",
  "stepId": "Step Id",
  "stepType": "Step Type",
  "stepDescription": "Step Description",
  "previousStepId": "Previous Step Id",
  "maximumLoopCount": "Maximum Loop Count",
  "queueDecision": "Queue Decision",
  "erpControlKey": "ERP Control Key",
  "erpOperation": "ERP Operation",
  "erpWorkCenter": "ERP Work Center",
  "requiredTimeInProcess": "Required Time In Process",
  "specialInstruction": "Special Instruction",
  "erpSequence": "ERP Sequence",
  "blockPcusUntilInspectionFinished": "Block PCUs Until Inspection Finished",
  "entryStep": "Entry Step",
  "isLastReportingStep": "Is Last Reporting Step",
  "reworkStep": "Rework Step",
  routingStepDetails: "Routing Step Details",
  "routingDescription": "Router Description",

  "insertBefore": "Insert Before",
  "insertAfter": "Insert After",
  "createRouting": "Create Route",
  operation: "Operation",
  operationId: "Operation ID",
  "operationVersion": "Operation Version",
  selectMessageType: "Select Message Type",
  selectResource: "Select Resource",
  selectWorkCenter: "Select Work Center",

  // =========================================   ACTIVITY =============================================
  activityAppTitle: "Activity Maintenance",
  activity: "Activity",
  activityIds: "Activity Id",
  activityGroup: "Activity Group",
  enabled: "Enabled",
  visibleInActivityManager: "Visible In Activity Manager",
  type: "Type",
  classOrProgram: "Class / Program",
  listOfMethod: "List Of Method",
  createActivity: "Create Activity",
  activityRules: "Activity Rules",
  activityHooks: "Activity Hooks",
  userArgument: "User Argument",
  sites: "Sites",
  "hookableMethod": "Hookable Method",
  hookPoint: "Hook Point",
  rules: "Rules",
  setting: "Setting",
  addRules: "Add Rules",
  addRule: "Add Rule",
  restoreDefault: "Restore Default",
  selectActivity: "Selelct Activity",
  ok: "OK",

  // ===============================================  Work Center =========================

  workCenterAppTitle: "Work Center Maintenance",
  workCenterCategory: "Work Center Category",
  defaultParentWorkCenter: "Default Parent Work Center",
  defaultWorkCenter: "Default Work Center",
  createWorkCenter: "Create Work Center",
  association: "Association",
  associateId: "Associate Id",
  defaultResource: "Default Resource",
  deleteWCMessage: "Are you sure you want to delete this work center ",
  disabled: "Disabled",
  closeMsg: "Are you sure you want to leave the page?",
  yes: "Yes",
  no: "No",
  select: "Select",
  confirmation: "Confirmation",
  selectAssociateId: "Select Associate Id",
  closePageMsg: "Are you sure you want to exit?",
  leavePage: "Leave Page",

  "headerTitle": "Shift Maintenance",
  "siteMaintenance": "Site Maintenance",
  "batchNo": "Batch No",
  "pod": "Pod",
  "site": "Site",
  "shift": "Shift",
  "pcu": "PCU",
  "itemBO": "Item",
  "routerBO": "Router",
  "qty": "Quantity",
  "quantity": "Quantity",
  "shopOrderBO": "Shop Order",
  "timeZone": "Time Zone",
  "local": "Local",
  "shopOrder": "Shop Order",
  "userHeaderTitle": "User Maintenance",
  "underDeliveryTolerance": "Under Delivery ",
  "overDeliveryTolerance": "Over Delivery ",
  "maximumDeliveryQty": "Maximum Delivery Qty",
  "minimumDeliveryQty": "Minimum Delivery Qty",
  "user": "User",
  "noOfCount": "Cycle Time",
  "shiftType": "Shift Type",
  "material": "Product Code",
  "cycleTime": "Cycle Time",
  "manufacturedTime": "Production Time",
  "createCycleTime": "Create Cycle Time",
  "materialVersion": "Product Version",
  "update": "Update",
  "shiftInterval": "Shift Interval",
  "calendarRules": "Calendar Rules",
  "calendarOverride": "Calendar Override",
  "createdOn": "Created On",
  "modifiedOn": "Modified On",
  "erpShift": "ERP Shift",
  "alertRow": "Do you want to proceed with the selected row?",
  "areYouSure": "Are you sure you want to delete this",
  "addBreak": "Add Break",
  "Status": "Status",
  "comment": "Comment",
  "newStatus": "New Status",
  "selectBy": "Select By",
  "validityShiftInfo": "Validity/Shift Information",
  "clockInOutInfo": "Clock-In/Out Information",
  "labourInfo": "Labour Information",
  "action": "Action",
  "day": "Day",
  "productionDay": "Production Day",
  "data": "Data",
  "dayClass": "Day Class",
  "search": "Search",
  "maintenance": "Maintenance",
  "certification": "Certification",
  "subStep": "Sub-Step",
  "activityHook": "Activity Hook",
  "operationType": "Operation Type",
  "resourceType": "Resource Type",
  "defaultOperation": "Default Operation",
  "addAsErpOperation": "Add as ERP Operation",
  "maxLoopCount": "Max Loop Count",
  "enter": "Enter",
  "employeeNumber": "Employee Number",
  "hireDate": "Hire Date",
  "erpUser": "ERP User",
  "firstName": "First Name",
  "lastName": "Last Name",
  "emailAddress": "Email Address",
  "erpPersonnelNumber": "ERP Personal Number",
  "userGroup": "User Group",
  "labourTracking": "Labour Tracking",
  "supervisor": "Supervisor",
  "labourRule": "Labour Rule",
  "bomType": "BOM Type",
  "plannedBom": "Planned BOM",
  "plannedRouting": "Planned Routing",
  "lcc": "LCC",
  "plannedWorkCenter": "Planned Work Center",
  "orderedQty": "Ordered Qty",
  "priority": "Priority",
  "buildQty": "Build Qty",
  "erpUom": "ERP UOM",
  "plannedStart": "Planned Start",
  "plannedCompletion": "Planned Completion",
  "scheduledStart": "Scheduled Start",
  "scheduledEnd": "Scheduled End",
  "customerOrder": "Customer Order",
  "customer": "Customer",
  "orderType": "Order Type",
  "plannedMaterial": "Planned Material",
  "productionQuantities": "Production Quantities",
  "serialPCU": "Serial PCU",
  "enable": "Enable",
  "serialNumber": "Serial Number",
  "pcuNumber": "PCU Number",
  "pcuQuantity": "PCU Quantity",
  "state": "State",
  "defineDeliveryToleranceIn": "Delivery Tolerance In",
  "unlimited_over_delivery": "Unlimited Over Delivery",
  "bomMaintenance": "BOM Maintenance",
  "bomTemplate": "BOM Template",
  "component": "Component",
  "assemblyOperation": "Assembly Operation",
  "assemblyQuantity": "Assembly Quantity",
  "copyBom": "Copy BOM",
  "updateBom": "Update BOM",
  "assemblySequence": "Assembly Sequence",
  "componentType": "Component Type",
  "maxNc": "Max NC",
  "maxUsage": "Max Usage",
  "storageLocation": "Storage Location",
  "createBomComponent": "Create BOM Component",
  "createNewBom": "Create New BOM",
  "alternateComponentVersion": "Alternate Component Version",
  "designCost": "Design Cost",
  "assySequence": "Assembly Sequence",
  "componentVersion": "Component Version",
  "componentDescription": "Component Description",
  "assyQty": "Assembly Quantity",
  "assyOperation": "Assembly Operation",
  "assemblyDataTypeBo": "Assembly Data Type",
  "storageLocationBo": "Storage Location",
  "close": "Close",
  "availableActivities": "Available Activities",
  "assignedActivities": "Assigned Activities",
  "activities": "Activities",
  "activityGroupName": "Activity Group Name",
  "activityGroupMaintenance": "Activity Group Maintenance",
  "createActivityGroup": "Create Activity Group",
  "activityGroupDescription": "Activity Group Description",
  "copyActivityGroup": "Copy Activity Group",
  container: "Container",
  selectContainer: "Select Container",



  // ===============================   Next Number     ==============================
  "recipientName": "Recipient Name",
  "recipientId": "Recipient ID",
  "numbeType": "Number Type",
  "definedBy": "Defined By",
  "objectVersion": "Object Version",
  "containerInput": "Container Input",
  "prefix": "Prefix",
  "suffix": "Suffix",
  "numberBase": "Number Base",
  "doneQty": "Done Quantity",
  "releasedQty": "Released Quantity",
  "qtyInQueueOrWork": "Quantity in Queue",
  "scrappedQty": "Scrapped Quantity",
  "unreleasedQty": "Unreleased Quantity",
  "sequenceLength": "Sequence Length",
  "minSequence": "Min Sequence",
  "maxSequence": "Max Sequence",
  "warningThreshold": "Warning Threshold",
  "incrementBy": "Increment By",
  "currentSequence": "Current Sequence",
  "resetSequenceNumber": "Reset Sequence Number",
  "nextNumberActivity": "Next Number Activity",
  "createContinuousSfc": "Create Continuous PCU on Import",
  "commitNextNumberChangesImmediately": "Commit Next Number Changes Immediately",
  "sampleNextNumber": "Sample Next Number",
  "nextNumberAppTitle": "Next Number Maintenance",
  "parametersAndDescription": "Parameter And Description",
  "selectItemGroup": "Select Item Group",
  "selectDataType": "Select DataType",
  "selectBOM": "Select BOM",
  "selectItem": "Select Item",
  "retrieve": "Retrieve",
  "clear": "Clear",
  "createNextNumber": "Create Next Number",
  "deleteMsg": "Do you want to delete this next number?",
  "sl_no": "Sl No",
  "packet_id": "Packet ID",
  "packet_description": "Packet Description",
  "qty_consumed": "Qty Consumed",
  "total_packets": "Total Packets",
  "remaining_capacity": "Remaining Capacity",

  "cycleTitle": "Cycle Time Maintenance",

  // ====================== Operational Settings ========================
  operationalSettingAppTitle: "Operational Setting",
  "uomAbb": "Unit of Measure",
  "reset": "Reset",
  "name": "Name",


  "podMaintenance": "Pod Maintenance",
  "podName": "Pod Name",
  "createPodName": "Create Pod Name",
  "podLayout": "Pod Layout",
  "kafkaIntegration": "Kafka Integration",
  "kafkaId": "Kafka ID",
  "operationCanBeChanged": "Operation Can Be Changed",
  "resourceCanBeChanged": "Resource Can Be Changed",
  "showQuantity": "Show Quantity",
  "documentName": "Document Name",
  "sessionTimeout": "Session Timeout",
  "refreshRate": "Refresh Rate",
  "podType": "Pod Type",
  "copyPod": "Copy Pod",
  "updatePod": "Update Pod",
  "buttonId": "Button ID",
  "buttonLabel": "Button Label",
  "buttonType": "Button Type",
  "buttons": "Buttons",
  "listOptions": "List Options",
  "podSelections": "Pod Selections",
  "printers": "Printers",
  "home": "Home",
  "buttonSize": "Button Size",
  "imageIcon": "Image Icon",
  "hotKey": "Hot Key",
  "buttonLocation": "Button Location",
  "podSelection": "POD SELECTION",
  "activitySequence": "Activity Sequence",
  "pluginLocation": "Plugin Location",
  "clearsPcu": "Clear PCU",
  "fixed": "Fixed",
  "createNewPod": "Create New Pod",
  "panelLayout": "Panel Layout",
  "selectDefaultOperation": "Select Default Operation",
  "selectDefaultResource": "Select Default Resource",
  "selectDocumentName": "Select Document Name",
  "browseWorkList": "Browse Work List",
  "podWorkList": "POD Work List",
  "assembleList": "Assemble List",
  "dcCollectList": "DC Collect List",
  "toolList": "Tool List",
  "workInstructionList": "Work Instruction List",
  "dcEntryList": "DC Entry List",
  "subStepList": "Sub Step List",
  "mainInput": "Main Input",
  "mainInputHotKey": "Main Input Hot Key",
  "infoLine1": "Info Line 1",
  "infoLine2": "Info Line 2",
  "documentPrinter": "Document Printer",
  "labelPrinter": "Label Printer",
  "travelerPrinter": "Traveler Printer",
  "recommendedBuildQtyToReachOrderedQty": "Reach Ordered Qty",
  "recommendedBuildQtyToReachMinimumDeliveryQty": "Reach Minimum Qty",
  "generalInfo": "General Information",
  "materialCode": "Material Code",
  "materialDescription": "Product Name",
  "purchaseOrderNumber": "Purchase Order Number",
  "grnNumber": "GRN Number",
  "supplierInfo": "Supplier Information",
  "supplierName": "Supplier Name",
  "supplierId": "Supplier ID",
  "invoiceNumber": "Invoice Number",
  "warehouseCode": "Warehouse Code",
  "storageBin": "Storage Bin",
  "deliveryInfo": "Delivery Information",
  "deliveryNumber": "Delivery Number",
  "deliveryType": "Delivery Type",
  "vehicleNumber": "Vehicle Number",
  "inwardDetails": "Inward Details",
  "receiptDateTime": "Receipt Date & Time",
  "gateDockNumber": "Gate Dock Number",
  "attachmentDocument": "Attachment Document",
  "attachment": "Attachment",
  "materialInwardManagement": "Material Inward Management",


  // ============================ Consumption and packing =====================
  "consumptionAndPackingAppTitle": "Consumption And Packing",

  "users": "Users",
  "userGroupMaintenance": "User Group Maintenance",
  "selectPod": "Select Pod",
  "availableUsers": "Available Users",
  "assignedUsers": "Assigned Users",
  "availableActivityGroups": "Available Activity Groups",
  "assignedActivityGroups": "Assigned Activity Groups",
  "pickListManagement": "Pick List Management",
  "pickListNo": "Pick List No",
  "orderNo": "Order No",
  "generate": "Generate",
  "itemCode": "Item Code",
  "itemDescription": "Item Description",
  "qtyOrdered": "Qty Ordered",
  "qtyPicked": "Qty Picked",
  "location": "Location",
  "warehouse": "Warehouse",
  "pick": "Pick",
  "updatePick": "Update Pick",
  "print": "Print",
  "selectOrder": "Select Order",
  "resourceMaintenance": "Resource Maintenance",
  "createResource": "Create Resource",
  "createList": "Create List",
  "opcTag": "OPC Tag",
  "processResource": "Process Resource",
  "erpEquipmentNumber": "ERP Equipment Number",
  "erpPlantNumber": "ERP Plant Number",
  "availableResource": "Available Resource",
  "assignedResource": "Assigned Resource",
  "tagName": "Tag Name",
  "tagUrl": "Tag URL",
  "identity": "Identity",
  "selectCertification": "Select Certification",
  "cycleTimeMaintenance": "Cycle Time Maintenance",
  "dataType": "Data Type",
  "selectRouting": "Select Routing",
  "manageAlternateComponents": "Manage Alternate Components",
  "manageParentComponents": "Manage Parent Components",
  "selectComponent": "Select Component",
  "selectAssemblyOperation": "Select Assembly Operation",
  "selectAssemblyDataType": "Select Assembly Data Type",
  "selectAlternateComponent": "Select Alternate Component",
  "selectOperation": "Select Operation",
  "selectMaterial": "Select Material",
  "uomCode": "UOM Code",
  "selectList": "Select List",
  "list": "List",
  "selectPrinters": "Select Printers",
  "parameter": "Parameter",
  "enterFullScreen": "Enter Full Screen",
  "exitFullScreen": "Exit Full Screen",
  "release": "Release",
  "shopOrderRelease": "Shop Order Release",
  "qtyToRelease": "Quantity to Release",
  "addToNewProcessLot": "Add to New Process Lot",
  "availableQtyToRelease": "Available Quantity to Release",
  "flowChart": "Flow Chart",
  "serialBatchNumber": "Serial Batch Number",
  "bnoQuantity": "BNO Quantity",
  "bno": "BNO",
  "erpPlantMaintenanceOrder": "ERP Plant Maintenance Order",
  "availableResourceTypes": "Available Resource Types",
  "assignedResourceTypes": "Assigned Resource Types",
  "copyResource": "Copy Resource",
  'productCode' : 'Product Code',

  // ==========================LIST APP=========================================

  "allowOperatorToChangeColumnSequence": "Allow Operator To Change Column Sequence",
  "allowOperatorToSortRows": "Allow Operator To Sort Rows",
  "allowMultipleSelection": "Allow Multiple Selection",
  "showAllActiveSfcsToOperator": "Show All Active SFCs To Operator",
  "maximumNumberOfRow": "Maximum Number Of Row",
  "columnSequence": "Sequence",
  "columnName": "Column Name",
  "rowSortOrder": "Row Sort Order",
  "ShowDetails": "Show Details",
  "width": "Width",
  "ascending": "Ascending",
  "descending": "Descending",
  "copyList": "Copy List",
  "deleteConfirmation": "Delete Confirmation",
  "ListMaintenance": "List Maintenance",

  // ============================ Item Group =====================
  "itemGroupAppTitle": "Item Group Maintenance",
  "groupDescription": "Group Description",
  "unitPrice": "Unit Price",
  "groupMember": "Group Member",
  "createItemGroup": "Create Item Group",
  "itemGroupDeleteMessage": "Do you want to delete this item group",
  "availableItems": "Available Items",
  "assignedItems": "Assigned Items",
  "selectMethod": "Select Method",
  "method": "Method",
  "resourceTypeMaintenance": "Resource Type Maintenance",
  "resourceTypeDescription": "Resource Type Description",
  "resourceMemberList": "Resource Member List",
  "createResourceType": "Create Resource Type",
  "createUserGroup": "Create User Group",
  "customdataMaintenance": "Custom Data Maintenance",
  "data field": "Data Field",
  "field label": "Field Label",
  "required": "Required",
  "selectdataField": "Select Data Field",


  // ============================================== DATA FIELD ===========================================
  "dataField": "Data Field",
  "fieldLabel": "Field Label",
  "dataFieldAppTitle": "Data Field Maintenance",
  "maskGroup": "Mask Group",
  "preSaveActivity": "Pre-Save Activity",
  "isTrackable": "Is Trackable",
  "qmSelectedSet": "QM Selected Set",
  "isMrfRef": "Is MFR Ref",
  "browseIcon": "Browse Icon",
  "defaultLabel": "Default Label",
  "fieldValue": "Field Value",
  "labelValue": "Label Value",
  "api": "API",
  "parameters": "Parameters",
  "title": "Title",
  "editValues": "Edit Values",
  "createDataField": "Create Data Field",

  // ============================================== DATA TYPE ===========================================
  "dataTypeAppTitle": "Data Type Maintenance",
  "createDataType": "Create Data Type",
  "selectDataField": "Select Data Field",
  "listDetails": "List Details",

  "order": "Order",
  "componentToScan": "Component to Scan",
  "assembled": "Assembled",
  "assemble": "Assemble",
  "remaining": "Remaining",
  "dataAttribute": "Data Attribute",
  "returnToPod": "Return to POD",
  "confirmCreateDataField": "Data Field not found, want to create this data field",

  // ============================================== DATA COLLECTION ===========================================
  "dataCollectionAppTitle": "Data Collection Maintenance",
  "dataCollection": "Data Collection",
  "createDC": "Create Data Collection",
  "collectionType": "Collection Type",
  "collectionDataAt": "Collection Data At",
  "collectDataAt": "Collect Data At",
  "erpGroup": "ERP Group",
  "qmInspectionGroup": "QM Inspection Group",
  "passOrFailGroup": "Pass or Fail Group",
  "failOrRejectNumber": "Fail or Reject Number",
  "userAuthenticationRequired": "User Authentication Required",
  "frequency": "Frequency",
  "parameterName": "Parameter Name",
  "parameterDetails": "Parameter Details",
  "prompt": "Prompt",
  "allowMissingValues": "Allow Missing Values",
  "displayDataValues": "Display Data Values",
  "falseValue": "False Value",
  "trueValue": "True Value",
  "formula": "Formula",
  "minValue": "Minimum Value",
  "maxValue": "Maximum Value",
  "targetValue": "Target Value",
  "softLimitCheckOnMinOrMaxValue": "Soft Limit Check on Min or Max Value",
  "overrideMinOrMax": "Override Min or Max",
  "autoLogNconMinOrMaxOverride": "Auto Log on Min or Max Override",
  "ncCode": "NC Code",
  "mask": "Mask",
  "unitOfMeasure": "Unit of Measure",
  "requiredDataEntries": "Required Data Entries",
  "optionalDataEntries": "Optional Data Entries",
  "attachmentDetails": "Attachment Details",
  "itemVersion": "Item Version",
  "attachmentList": "Attachment List",

  // ============================================= DC PLUGIN ===========================================
  "parameterList": "Parameter List",
  "showDetails": "Show Details",
  "collectData": "Collect Data",
  "saveDraft": "Save Draft",
  "submit": "Submit",
  "dataFieldList": "Data Field List",
  "collectedDCParameterList": "Collected DC Parameter List",
  "returnToDCList": "Return To DC List",
  "range": "Range",
  "dateTime": "DateTime",
  "collectionMethod": "Collection Method",

  // =============================================== WORK INSTRUCTION ======================================
  "textInstruction": "Text Instruction",
  "urlInstruction": "URL Instruction",
  "instructionType": "Instruction Type",
  "WorkInstruction_Description": "Description",
  "WorkInstructionID_Revision": "Work Instruction / Revision",
  "Operation_StepId": "Operation StepId",
  "StepId": "Step Id",


  "workInstructionMaintenance": "Work Instruction Maintenance",
  "workInstruction": "Work Instruction",
  "createWorkInstruction": "Create Work Instruction",
  "alwaysShowInNewWindow": "Always Show in New Window",
  "logViewing": "Log Viewing",
  "changeAlert": "Change Alert",
  "erpWi": "ERP Work Instruction",
  "text": "Text",
  "url": "URL",
  "file": "File",
  // ============================================== Change Machine Status ===========================================
  "machineStatusChange": "Machine Status Change",

  // ============================================== Scrap Unscrap ===========================================
  "pcu/shopOrder/processLot": "PCU / Shop Order / Process Lot",
  "comments": "Comments",
  "scrap": "Scrap",
  "unscrap": "Unscrap",
  "Scrap": "Scrap",
  "Unscrap": "Unscrap",
  "scrapUnscrapTitle": "Scrap Unscrap",

  // ============================================== User Maintenance ===========================================
  "confirmPassword": "Confirm Password",
  "password": "Password",
  "selectSites": "Select Sites",
  "workflowIntegrationMaintenance": "Workflow Integration Maintenance",
  "workflowIntegration": "Workflow Integration",
  "createWorkflowIntegration": "Create Workflow Integration",
  "identifier": "Identifier",
  "messageId": "Message ID",
  "processBy": "Process By",
  "transformationType": "Transformation Type",
  "preprocessJolt": "Pre-Process Jolt",
  "preprocessApi": "Pre-Process API",
  "serviceApi": "Service API",
  "expectedSplits": "Expected Splits",
  "postProcessJolt": "Post-Process Jolt",
  "postProcessApi": "Post-Process API",
  "passHandler": "Pass Handler",
  "failHandler": "Fail Handler",
  "processTransformation": "Process Transformation",

  // ============================================== Jolt Spec ===========================================
  "specName": "Spec Name",
  "specNamePlaceholder": "Enter spec name",
  "specNameRequired": "Please input spec name!",
  "typePlaceholder": "Select type",
  "typeRequired": "Please select a type!",
  "joltSpec": "Jolt Spec",
  "joltSpecPlaceholder": "Enter Jolt specification",
  "xsltSpec": "XSLT Spec",
  "xsltSpecPlaceholder": "Enter XSLT specification",
  "encodeXsltSpec": "Encode XSLT Spec",
  "encodeXsltSpecPlaceholder": "Enter encoded XSLT specification",
  "jsonAtaSpec": "Jsonata Spec",
  "jsonAtaPlaceholder": "Enter JsonAta specification",
  "encodedJsonAtaSpec": "Encoded JsonAta Spec",
  "encodedJsonAtaSpecPlaceholder": "Enter encoded JsonAta specification",

  "joltAppTitle": "Jolt Spec Maintenance",
  "createSpec": "Create Spec",
  "encode": "Encode",
  "decode": "Decode",
  "spec": "Spec",
  "decodeXsltSpec": "Decoded XSLT Specification",
  "decodeJsonAtaSpec": "Decoded JsonAta Specification",

  "show": "Show",
  "joltSpecification": "Jolt Specification",
  "jsonataSpecification": "Jsonata Specification",
  "xsltSpecification": "Xslt Specification",
  "eventIntervalSeconds": "Event Interval Seconds",
  "cronExpression": "Cron Expression",
  "edit": "Edit",
  "runJob": "Run Job",
  "stopScheduler": "Stop Scheduler",

  "apiToProcess": "API to Process",
  "selectPreProcessJolt": "Select Pre-Process Jolt",
  "selectPostProcessJolt": "Select Post-Process Jolt",
  "selectPreProcessXSLT": "Select Pre-Process XSLT",
  "processJoltXslt": "Process Jolt XSLT",
  "splitConfigurations": "Split Configurations",
  "splitIdentifier": "Split Identifier",

  "conditional": "Conditional",
  "parallel": "Parallel",
  "anyOrder": "Any Order",
  "orderNumber": "Order Number",
  "recipeVersion": "Recipe Version",
  "recipeNo": "Recipe Number",
  "recipeDescription": "Description",
  "targetQuantity": "Target Quantity",
  "startDate": "Start Date",
  "finishDate": "Finish Date",
  "schedFinTime": "Scheduled Finish Time",
  "schedStartTime": "Scheduled Start Time",
  "selectRecipeNo": "Select Recipe Number",
  "batchNumber": "Batch Number",
  "batchNumberQuantity": "Batch Number Quantity",

  // ============================================== Process Order Plugin ===========================================
  "complete": "Complete",
  "start": "Start",


  // ============================================== NC Group ===========================================
  "ncGroup": "NC Group",
  "ncGroups": "NC Groups",
  "ncGroupAppTitle": "NC Group Maintenance",
  "availableNcGroups": "Available NC Groups",
  "assignedNcGroups": "Assigned NC Groups",
  "ncGroupFilterPriority": "NC Group Filter Priority",
  "validAtAllOperations": "Valid At All Operations",
  "parameterBo": "Parameter",
  "operationBO": "Operation",
  "dcGroupBO": "DC Group",
  "pcuBO": "PCU",
  "testDateTime": "Test Date Time",
  "dcGroupDescription": "DC Group Description",
  "subStepID": "Sub Step ID",
  "measureStatus": "Measure Status",
  "measureType": "Measure Type",
  "highLimit": "High Limit",
  "lowLimit": "Low Limit",
  "expected": "Expected",
  "actualNum": "Actual Number",
  "dcComment": "DC Comment",
  "usedLimitSeq": "Used Limit Sequence",
  "elapsedTime": "Elapsed Time",
  "originalActual": "Original Actual",
  "originalDcComment": "Original DC Comment",
  "originalTestDateTime": "Original Test Date Time",
  "edited": "Edited",
  "editedUserBO": "Edited User",
  "editedDateTime": "Edited Date Time",
  "internalMeasureID": "Internal Measure ID",
  "routingBO": "Routing",
  "stepID": "Step ID",
  "userBO": "User",
  "overrideUserBO": "Override User",
  "dcGroupVersion": "DC Group Version",
  "erpSent": "ERP Sent",
  "qmaccepted": "QM Accepted",
  "detailInformation": "Detail Information",
  "detail": "Detail",
  "dcGroup": "DC Group",
  "viewPdf": "View PDF",
  "createNCGroup": "Create NC Group",
  "ncCodeDPMOCategory": "NC Code DPMO Category",
  "operationList": "Operation List",
  "ncGroupDeleteMessage": "Do you want to delete this NC Group",
  "availableNCCodes": "Available NC Codes",
  "assignNCCodes": "Assign NC Codes",
  "assignedNC": "Assigned NC",
  "availableNC": "Available NC",

  "logNc": "Log NC",
  "done": "Done",

  "NcCodeMaintenance": "NC Code Maintenance",
  "NC Code": "NC Code",
  "operationGroups": "Operation Groups",
  "dispositionRoutings": "Disposition Routings",
  "NC Groups": "NC Groups",
  "secondaries": "Secondaries",
  "createNcCode": "Create NC Code",
  "assignNCtoComponent": "Assign NC to Component",
  "ncCategory": "NC Category",
  "dpmoCategory": "DPMO Category",
  "ncDatatype": "NC Datatype",
  "collectRequiredNCDataonNC": "Collect Required NC Data on NC",
  "ncPriority": "NC Priority",
  "maximumNCLimit": "Maximum NC Limit",
  "ncSeverity": "NC Severity",
  "secondaryCodeSpecialInstruction": "Secondary Code Special Instruction",
  "canBePrimaryCode": "Can be Primary Code",
  "closureRequired": "Closure Required",
  "autoClosePrimaryNC": "Auto Close Primary NC",
  "autoCloseIncident": "Auto Close Incident",
  "secondaryRequiredForClosure": "Secondary Required for Closure",
  "erpQNCode": "ERP QN Code",
  "erpCatalog": "ERP Catalog",
  "erpCodeGroup": "ERP Code Group",
  "erpCode": "ERP Code",
  "oeeQualityKPIRelevant": "OEE Quality KPI Relevant",
  "selectNcDatatype": "Select NC Datatype",
  "validOperations": "Valid Operations",
  "dispositionGroups": "Disposition Groups",
  "availableRouting": "Available Routing",
  "assignedRouting": "Assigned Routing",
  "availableSecondaries": "Available Secondaries",
  "assignedSecondaries": "Assigned Secondaries",
  "copyNcCode": "Copy NC Code",
  "toolNumberMaintenance": "Tool Number Maintenance",
  "toolNumber": "Tool Number",
  "toolGroup": "Tool Group",
  "qtyAvailable": "Quantity Available",
  "erpPlanMaintenanceOrder": "ERP Plan Maintenance Order",
  "toolQty": "Tool Quantity",
  "createToolNumber": "Create Tool Number",
  "calibration": "Calibration",
  "measurementPoints": "Measurement Points",
  "measurementPoint": "Measurement Point",
  "calibrationType": "Calibration Type",
  "calibrationPeriod": "Calibration Period",
  "calibrationCount": "Calibration Count",
  "maximumCalibrationCount": "Maximum Calibration Count",
  "expirationDate": "Expiration Date",
  "displayClosedNc": "Display Closed NC",
  "selectRoute": "Select Route",
  "customOrder": "Custom Order",
  "createToolGroup": "Create Tool Group",
  "timeBased": "Time Based",
  "quantityRequired": "Quantity Required",
  "trackingControl": "Tracking Control",
  "toolGroupMaintenance": "Tool Group Maintenance",
  "listConfiguration": "List Configuration",
  "multiProcessOrderRelease": "Multi Process Order Release",
  "multiProcessOrder": "Multi Process Order",
  "mrpController": "MRP Controller",
  "productionScheduler": "Production Scheduler",
  "reservationNumber": "Reservation Number",
  "productionStartDate": "Production Start Date",
  "productionFinishDate": "Production Finish Date",
  "actualStartDate": "Actual Start Date",
  "actualFinishDate": "Actual Finish Date",
  "inUse": "In Use",
  "measuredUom": "Measured Uom",
  "entryPhase": "Entry Phase",
  "exitPhase": "Exit Phase",
  "entryOperation": "Entry Operation",
  "lastOperationAtPhase": "Last Operation At Phase",
  "nextPhase": "Next Phase",

  "accept": "Accept",
  "reject": "Reject",
  "partial": "Partial",
  "skip": "Skip",
  "buyOff": "Buy Off",
  "username": "User Name",
  "userAuthentication": "User Authentication",
  "login": "Login",
  // ======================================= Certification Maintenance ===========================================
  "certificationmaintenance": "Certification Maintenance",
  "certifications": "Certifications",
  "createCertification": "Create Certification",
  "durationType": "Duration Type",
  "maxNumberOfExtensions": "Max Number of Extensions",
  "maxExtensionDuration": "Max Extension Duration",
  "assignment": "Assignment",
  "availableUserGroups": "Available User Groups",
  "assignedUserGroups": "Assigned User Groups",
  "measurementpoints": "Measurement Points",
  "copyCertification": "Copy Certification",
  // ============================================== Line Clearance ===========================================
  "lineClearanceMaintenance": "Line Clearance Maintenance",
  "lineClearance": "Line Clearance",
  "templateName": "Template Name",
  "clearanceTimeLimit": "Clearance Time Limit",
  "maxPendingTasks": "Max Pending Tasks", 
  "clearanceReminderInterval": "Clearance Reminder Interval",
  "notifyOnCompletion": "Notify On Completion",
  "enablePhotoEvidence": "Enable Photo Evidence",
  "associated": "Associated",
  "workcenterId": "Workcenter ID",
  "resourceName": "Resource Name",
  "createLineClearance": "Create Line Clearance",
  "taskid": "Task ID",
  "taskname": "Task Name",
  "mandatory": "Mandatory",
  "evidencerequired": "Evidence Required",
  "userRoles": "User Roles",
  "userid": "User ID",
  "permissions": "Permissions",
  "selectUser": "Select User",

  "activityId": "Activity Id",
  "selectPcu": "Select Pcu",
  "selectBatchNo": "Select Batch No",
  "createPodMaintenance": "Create Pod Maintenance",
  "reloadWorkList": "Reload Work List",
  "reloadResource": "Reload Resource",
  "settings": "Settings",
  "layout": "Layout",
  "PCUOrBatchNumberBrowseActivity": "PCU Or Batch Number Browse Activity",
  "PodWorkListActivity": "Pod Work List Activity",
  "ButtonActivityInWork": "Button Activity in Work",
  "ButtonActivityInQueue": "Button Activity in Queue",
  "OnTabOutOfOperation": "On Tab Out of Operation",
  "OnTabOutOfWorkcenter": "On Tab Out of Workcenter",
  "OnTabOutOfResource": "On Tab Out of Resource",
  "UpdateFieldsToSession": "Update Fields To Session",
  "panel": "Panel",
  "defaultPlugin": "Default Plugin",
  "otherPlugin": "Other Plugin",
  "scrapQuantity": "Scrap Quantity",
  "subPod": "Sub Pod",
  "podCategory": "Pod Category",
  "buttonActivityInQueue": "Button Activity In Queue",
  "buttonActivityInWork": "Button Activity In Work",
  "activityDescription": "Activity Description",
  "workListPanel": "Work List Panel",
  "uomConversion": "UOM Conversion",
  "conversion": "Conversion",
  "materialCountConversion": "Material Count Conversion",
  "convertUom": "Convert UOM",
  "baseUnit": "Base Unit",
  "conversionUnit": "Conversion Unit",
  "conversionFactor": "Conversion Factor",
  "trackOee": "Track OEE",
  "conversionDeleteMessage": "Do you want to delete this conversion?",
  "baseAmt": "Base Amount",
  "convertionItem": "Convertion Item",
  "areYouSureDeleteThisSplit": "Are you sure you want to delete this split?",
  "attach": "Attach",
  "filePreview": "File Preview",
  "change": "Change",
  "preview": "Preview",
  "defaultPhaseId": "Default Phase ID",
  "reloadSiteConfirmation": "Are you sure you want to reload site?",
  "phaseCanBeChanged": "Phase Can Be Changed",
  "showResource": "Show Resource",
  "showOperation": "Show Operation",
  "showPhase": "Show Phase",
  "auditLogReport": "Audit Log Report",
  "dataCollectionReport": "Data Collection Report",
  "dataCollectionGraph": "Data Collection Graph",
  "selectCategory": "Select Category",
  "currentSetting": "Current Setting",
  "date/time": "Date/Time",
  "changeType": "Change Type",
  "dateRange": "Date Range",
  "time": "Time",
  "topicConfiguration": "Topic Configuration",
  "createTopicConfiguration": "Create Topic Configuration",
  "topicName": "Topic Name",
  "apiUrl": "API URL",
  "taskDescription": "Task Description",
  "evidence": "Evidence",
  "startedDateTime": "Started Date Time",
  "completedDateTime": "Completed Date Time",
  "reason": "Reason",
  "approved": "Approved",
  "approvedDateTime": "Approved Date Time",
  "approvedBy": "Approved By",
  "rejectedDateTime": "Rejected Date Time",
  "rejectedBy": "Rejected By",
  "updatedDateTime": "Updated Date Time",
  "updatedBy": "Updated By",
  "startedBy": "Started By",
  "completedBy": "Completed By",
  "taskName": "Task Name",
  "isMandatory": "Is Mandatory",
  "evidenceRequired": "Evidence Required",
  "theme": "Theme",
  "cycleTime(sec)": "Cycle Time (sec)",

  "shiftStart": "Shift Start",
  "shiftEnd": "Shift End",
  "shiftAvailableTime": "Shift Available Time",
  "totalBreakHours": "Total Break Hours",
  "createdDatetime": "Created Datetime",
  "updatedDatetime": "Updated Datetime",
  "createdBy": "Created By",
  "eventData": "Event Data",
  "plant": "Plant",
  "eventType": "Event Type",
  "buyOffAction": "Buy Off Action",
  "history": "History",
  "endDate": "End Date",
  "selectSite": "Select Site",
  "downtimeType": "Downtime Type",
  "selectStatus": "Select Status",
  "selectNewStatus": "Select New Status",
  "selectBatchNumber": "Select Batch Number",
  "selectOrderNumber": "Select Order Number",
  "batchStepStatus": "Batch Step Status",
  "PhaseId": "Phase Id",
  "InQueueQty": "In Queue Qty",
  "InWorkQty": "In Work Qty",
  "CompleteQty": "Complete Qty",
  "ScrapQty": "Scrap Qty",
  "batchStartedTime": "Batch Started Time",
  "batchCompletedTime": "Batch Completed Time",
  "level": "Level",
  "message": "Message",
  "approval": "Approval",

  "activityHookId": "Activity Hook ID",
  "targetClass": "Target Class",
  "targetMethod": "Target Method",
  "hookType": "Hook Type",
  "hookClass": "Hook Class",
  "hookMethod": "Hook Method",
  "executionMode": "Execution Mode",

  "hookAppTitle": "Activity Hook Maintenance",
  "createHook": "Create Hook",
  "hook": "Hook",
  "activityHookDeleteMessage": "Do you want to delete this Activity Hook",
  "logo": "Logo",
  "background": "Background",
  "color": "Color",
  "lineColor": "Line Color",

  "plannedCycleTime": "Planned Cycle Time",
  "actualCycleTime": "Actual Cycle Time",
  "totalBreakInMinutes": "Total Break (min)",

 
  "serviceExtension": "Service Extension",
  "createServiceExtension": "Create Service Extension",
  "createExtension": "Create Extension",
  "serviceExtensionAppTitle": "Service Extension Maintenance",
  "selectResourceType": "Select Resource Type",
  "executionPointId": "Execution Point ID",
  "extensionDeleteMessage": "Do you want to delete this extension",
  "executionPoint": "Execution Point",
  "extensionActivity": "Extension Activity",
  "MaterialDescription": "Material Description",
  "releaseTime": "Release Time",
  "unitOfMeasurement": "Unit Of Measurement",
  "releaseOrder": "Release Order",
  "createdDateTime": "Created Date Time",
  "releaseQty": "Release Qty",
  "productionTime": "Production Time",
  "downloadDate":"Download Date",
  "productName" : "Product Name",
  "batchStatus": "Batch Status",


  "createConfiguration": "Create Configuration",
  "apiConfiguration": "API Configuration",
  "storedProcedure": "Stored Procedure",
  "httpMethod": "HTTP Method",
  "inputParameters": "Input Parameters",
  "outputStructure": "Output Structure",
  "apiName": "API Name",
  "deleteApiConfigMessage": "Do you want to delete this configuration",
  "apiConfigMaintenance": "API Configuration Maintenance",
  "configuration": "Configuration",

  "shiftId": "Shift Id",
  "selectShift": "Select Shift",

  "approvalWorkFLowDetails": "Approval Workflow Details",
  "approvalLevelConfiguration": "Approval Level Configuration",
  "advancedConfiguration": "Advanced Configuration",
  "userRole": "User Role",
  "finalApproval": "Final Approval",
  "approvalWorkFlowConfiguration": "Approval Workflow Configuration",
  "workflow": "Workflow",
  "createApprovalWorkflowConfiguration": "Create Approval Workflow Configuration",
  "reviewDate":"Review Date",
  "view":"View",

  "productGroup":"Product Group",
  "selectProductGroup":"Select Product Group",

  "createComponent": "Create Component",
  "defaultValue": "Default value",
  "componentLabel": "Component Label",
  "validation": "Validation",
  "componentBuilderMaintenance": "Componenet Builder",
  "noOfColumns": "No. of columns",

  "workflowStates": "Workflow States",
  "states": "States",
  "editableFields": "Editable Fields",
  "appliesTo": "Applies To",
  "isActive": "Is Active",
  "isEnd": "Is End",
  "resourceDetails": "Resource Details",
  "createState": "Create State",
  "workflowStatesMaster": "Workflow States Master",
  "workflowStatusMaster": "Workflow Status Master",
  "createWorkflowStatusMaster": "Create Workflow Status Master",


  "from": "From",
  "to": "To",
  "attachmentType": "Attachment Type",
  "attachedTo": "Attached To",
  "attachedStatus": "Attachment Status",
  "default": "Default",
  "workFlowConfiguration": "Work Flow Configuration",
  "userRoleConfiguration": "User Role Configuration",

}
