export const hindiLanguage = {
  "schedulerMaintenance": "शेड्यूलर रखरखाव",
  "max": "अधिकतम",
  "min": "न्यूनतम",
  "tolerance": "टॉलरेंस",
  "actualValue": "वास्तविक मूल्य",
  "actionsOnFailure": "विफलता पर कार्रवाई",
  "monitoringFrequency": "निगरानी आवृत्ति",
  "expectedValue": "अपेक्षित मूल्य",
  "qcId": "क्यूसी आईडी",
  "expectedValueRange_hi": "अपेक्षित मूल्य सीमा",
  "frequency": "आवृत्ति",
  "dataPointID": "डेटा प्वाइंट आईडी",
  "pressure": "दबाव",
  "duration": "अवधि",
  "rpm": "आरपीएम",
  "workCenterId": "कार्य केंद्र आईडी",
  "resourceId": "संसाधन आईडी",
  "adjustments": "समायोजन",
  "qualityControlParameters": "गुणवत्ता नियंत्रण पैरामीटर",
  "dataCollection": "डेटा संग्रह",
  "resources_hi": "संसाधन",
  "tools": "उपकरण",
  "safetyProcedures": "सुरक्षा प्रक्रियाएँ",
  "yieldWasteTracking": "उत्पादकता और अपशिष्ट ट्रैकिंग",
  "triggerPoints": "ट्रिगर बिंदु",
  "packagingLabeling": "पैकेजिंग लेबलिंग",
  "ccp": "सीसीपी",
  "stepName": "चरण नाम",
  "instruction": "निर्देश",
  "steps": "चरण",
  "id_hi": "आईडी",
  "associatedStep": "संबंधित चरण",
  "expectedCycleTime": "अपेक्षित चक्र समय",
  "ingredients": "सामग्री",
  "phases": "चरण",
  "phaseId": "चरण आईडी",
  "phaseName": "चरण का नाम",
  "phasesName": "चरणों के नाम",
  "inactive": "निष्क्रिय",
  "recipeId": "रेसिपी आईडी",
  "batchSize": "बैच आकार",
  "batchUom": "बैच यूनिट",
  "totalExpectedCycleTime": "कुल अपेक्षित चक्र समय",
  "totalActualCycleTime": "कुल वास्तविक चक्र समय",
  "active": "सक्रिय",
  "recipeStepDetails": "रेसिपी चरण विवरण",
  "workInstructions": "कार्य निर्देश",
  "dataCollections": "डेटा संग्रहण",
  "parameterLists": "पैरामीटर सूची",
  "classification": "वर्गीकरण",
  "relaxedRecipeFlow": "आरामदायक प्रवाह नुस्खा",
  "scan": "स्कैन",
  "shipmentOrderNumber": "शिपमेंट ऑर्डर नंबर",
  "dispatchDetails": "वितरण विवरण",
  "dispatchDateTime": "वितरण दिनांक और समय",
  "recipientInfo": "प्राप्तकर्ता जानकारी",
  "dispatchInfo": "वितरण जानकारी",
  "stageType": "स्टेज प्रकार",
  "recipeSteps": "रेसिपी चरण",
  "recipeType": "विधि प्रकार",
  "recipe": "विधि",
  "recipeName": "विधि",
  "recipeDescription": "विवरण",
  "stage": "स्टेज",
  "processOrderRelease": "प्रक्रिया आदेश रिलीज़",
  "releaseProcessOrder": "रिलीज़ प्रक्रिया आदेश",
  "processOrder": "प्रक्रिया आदेश",
  "appTitle": "आइटम मेंटेनेंस",

  "item": "आइटम",
  "description": "विवरण",
  "resourceTypeDescription": "विवरण",
  "shiftType": "शिफ्ट प्रकार",
  "searchActivities": "गतिविधियों को खोजें",
  "logout": "लॉगआउट",
  "revision": "संशोधन",
  "qtyConsumed": "खपत की गई मात्रा",
  "status": "स्थिति",
  "procurementType": "क्रय प्रकार",
  "lotSize": "लॉट आकार",
  "createShift": "शिफ्ट बनाएं",
  "workCenter": "वर्क सेंटर",
  "resource": "संसाधन",
  "add": "जोड़ें",
  "main": "मुख्य",
  "alternateComponent": "वैकल्पिक घटक",
  "printDocument": "दस्तावेज़ प्रिंट करें",
  "customData": "कस्टम डेटा",
  "itemGroup": "आइटम समूह",
  "qtyRestriction": "मात्रा प्रतिबंध",
  "routing": "रूटिंग",
  "routingVersion": "रूटिंग संस्करण",
  "bom": "बीओएम",
  "bomVersion": "बीओएम संस्करण",
  "assemblyDataType": "असेंबली डेटा प्रकार",
  "removalDataType": "हटाने का डेटा प्रकार",
  "receiptDataType": "रसीद डेटा प्रकार",
  "currentVersion": "वर्तमान संस्करण",
  "itemType": "आइटम प्रकार",
  "create": "बनाएं",
  "save": "सहेजें",
  "cancel": "रद्द करें",
  "sequence": "अनुक्रम",
  "version": "संस्करण",
  "hold": "रोकें",
  "receive": "प्राप्त करें",
  "reject": "अस्वीकृत करें",
  "clear": "स्पष्ट करें",
  "versions": "संस्करण: ",
  "parentMaterial": "मूल पदार्थ",
  "validFrom": "से मान्य",
  "validTo": "तक मान्य",
  "createdDate": "निर्माण तिथि: ",
  "modifiedTime": "संशोधित समय: ",
  "availableDocuments": "उपलब्ध दस्तावेज़",
  "assignedDocuments": "असाइन किए गए दस्तावेज़",
  "document": "दस्तवेज़",
  "createItem": "आइटम बनाएं",
  "value": "मूल्य",
  "go": "जाएं",
  "copy": "कॉपी",
  "confirmCopy": "कॉपी की पुष्टि करें",
  "delete": "हटाएं",
  "confirmDelete": "हटाने की पुष्टि करें",
  "deleteMessage": "क्या आप इस आइटम को हटाना चाहते हैं?",
  "insert": "सम्मिलित करें",
  "removeSelected": "चयनित को हटाएं",
  "removeAll": "सभी को हटाएं",
  "generalInfo": "सामान्य जानकारी",
  "materialCode": "सामग्री कोड",
  "materialDescription": "सामग्री विवरण",
  "purchaseOrderNumber": "खरीद आदेश संख्या",
  "grnNumber": "GRN संख्या",
  "supplierInfo": "आपूर्तिकर्ता जानकारी",
  "supplierName": "आपूर्तिकर्ता नाम",
  "supplierId": "आपूर्तिकर्ता आईडी",
  "invoiceNumber": "चालान संख���या",
  "storageLocation": "भंडारण स्थान",
  "remove": "हटाएँ",
  "consumptionAndPackingAppTitle": "खपत और पैकिंग",
  "warehouseCode": "गोदाम कोड",
  "storageBin": "भंडारण बिन",
  "deliveryInfo": "डिलिवरी जानकारी",
  "deliveryNumber": "डिलिवरी संख्या",
  "deliveryType": "डिलिवरी प्रकार",
  "vehicleNumber": "वाहन संख्या",
  "inwardDetails": "आवक विवरण",
  "receiptDateTime": "प्राप्ति तिथि और समय",
  "gateDockNumber": "गेट डॉक संख्या",
  "attachmentDocument": "संलग्न दस्तावेज़",
  "attachment": "संलग्नक",

  // ===================================================
  "boxNumber": "बॉक्स नंबर",
  "boxCapacity": "बॉक्स क्षमता",
  "packetId": "पैकेट आईडी",
  "packetDescription": "पैकेट विवरण",
  "remainingCapacity": "शेष क्षमता",
  "totalPacketsInBox": "बॉक्स में कुल पैकेट",
  "sl_no": "क्रम संख्या",
  "packet_id": "पैकेट आईडी",
  "packet_description": "पैकेट विवरण",
  "qty_consumed": "खपत मात्रा",
  "total_packets": "कुल पैकेट",
  "remaining_capacity": "शेष क्षमता",

  "reasonCodeAppTitle": "कारण कोड मेंटेनेंस",
  "reasonCode": "कारण कोड",
  "category": "श्रेणी",
  "messageType": "संदेश प्रकार",
  "createReasonCode": "कारण कोड बनाएं",

  // ===================================================
  "prelautid": "पूर्व लाटिड",
  "materialName": "सामग्री का नाम",
  "uom": "मापने की इकाई",
  "expectedQty": "अपेक्षित मात्रा",
  "unit": "इकाई",
  "receivedQty": "प्राप्त मात्रा",
  "actions": "कार्य",
  "recipientName": "प्राप्तकर्ता का नाम",
  "recipientId": "प्राप्तकर्ता आईडी",
  "routingTitle": "रूटिंग रखरखाव",
  "routingType": "रूटिंग प्रकार",
  "routingSteps": "रूटिंग चरण",
  "subType": "उप प्रकार",
  "dispositionGroup": "निपटान समह",
  "relaxedRoutingFlow": "रिलैक्स्ड फ्लो रूटिंग",
  "replicationToErp": "ईआरपी के लिए प्रतिकृति",
  "details": "विवरण",
  "nextStepId": "अगले चरण आईडी",
  "stepId": "चरण आईडी",
  "stepType": "चरण प्रकार",
  "stepDescription": "चरण विवरण",
  "previousStepId": "पिछले चरण आईडी",
  "maximumLoopCount": "अधिकतम लूप गणना",
  "queueDecision": "क्यू निर्णय",
  "erpControlKey": "ईआरपी नियंत्रण कुंजी",
  "erpOperation": "ईआरपी ऑपरेशन",
  "erpWorkCenter": "ईआ��पी कार्य केंद्र",
  "requiredTimeInProcess": "प्रक्रिया में आवश्यक समय",
  "specialInstruction": "विशेष निर्देश",
  "erpSequence": "ईआरपी क्रम",
  "blockPcusUntilInspectionFinished": "निरीक्षण समाप्त होने तक PCUs को अवरुद्ध करें",
  "entryStep": "प्रवेश चरण",
  "isLastReportingStep": "अंतिम रिपोर्टिंग चरण है",
  "reworkStep": "पुनःकार्य चरण",
  "routingStepDetails": "रूटिंग चरण विवरण",
  "routingDescription": "ரௌட்டர் விளக்கம்",
  "insertBefore": "पहले सम्मिलित करें",
  "insertAfter": "बाद में सम्मिलित करें",
  "createRouting": "मार्ग बनाएं",
  "operation": "ऑपरेशन",
  "operationId": "ऑपरेशन आईडी",
  "operationVersion": "ऑपरेशन संस्करण",
  "selectMessageType": "संदेश प्रकार चुनें",
  "selectResource": "संसाधन चुनें",
  "selectWorkCenter": "वर्क सेंटर चुनें",
  "container": "कंटेनर",
  // ======================== Activity ======================
  "activityAppTitle": "गतिविधि प्रबंधन",
  "activity": "गतिविधि",
  "activityIds": "गतिविधि आईडी",
  "activityGroup": "गतिविधि समूह",
  "enabled": "सक्षम किया गया",
  "visibleInActivityManager": "गतिविधि प्रबंधक में दृश्य",
  "type": "प्रकार",
  "classOrProgram": "कक्षा / कार्यक्रम",
  "listOfMethod": "विधियों की सूची",
  "createActivity": "गतिविधि बनाएँ",
  "activityRules": "गतिविधि नियम",
  "activityHooks": "गतिविधि हुक्स",
  "userArgument": "उपयोगकर्ता तर्क",
  "sites": "साइट्स",
  "hookableMethod": "हुक करने योग्य विधि",
  "data": "डेटा",
  "hookPoint": "हुक पॉइंट",
  "rules": "नियम",
  "setting": "सेटिंग",
  "addRules": "नियम जोड़ें",
  "addRule": "नियम जोड़ें",
  restoreDefault: "डिफ़ॉल्ट पुनर्स्थापित करें",
  "selectActivity": "गतिविधि चुनें",
  // ========================== WORK CENTER ===========================
  "workCenterAppTitle": "कार्य केंद्र रखरखाव",
  "workCenterCategory": "कार्य केंद्र श्रेणी",
  "defaultParentWorkCenter": "डिफ़ॉल्ट अभिभावक कार्य केंद्र",
  "defaultWorkCenter": "डिफ़ॉल्ट कार्य केंद्र",
  "createWorkCenter": "कार्य केंद्र बनाएं",
  "association": "संगठन",
  "associateId": "एसोसिएट आईडी",
  "defaultResource": "डिफ़ॉल्ट संसाधन",
  "deleteWCMessage": "क्या आप वाकई इस कार्य केंद्र को हटाना चाहते हैं?",
  "disabled": "अक्षम",
  "closeMsg": "क्या आप वाकई पृष्ट छोड़ना चाहते हैं?",
  "yes": "हाँ",
  "no": "नहीं",
  "ok": "ठीक है",
  "select": "चुनें",
  "confirmation": "पुष्टि",
  "selectAssociateId": "सहयोगी आईडी चुनें",
  "closePageMsg": "क्या आप वाकई बाहर निकलना चाहते हैं?",
  "leavePage": "पृष्ठ छोड़ें",
  "router": "राउटर",

  "headerTitle": "शिफ्ट रखरखाव",
  "siteMaintenance": "साइट रखरखाव",
  "pod": "पॉड",
  "batchNo": "बैच संख्या",
  "shift": "शिफ्ट",
  "pcu": "पीसीयू",
  "itemBO": "आइटम ",
  "routerBO": "राउ",
  "qty": "मात्रा",
  "shopOrderBO": "दुकान आदेश ",
  "shopOrder": "शप ऑर्डर",
  "userHeaderTitle": "उपयोगकर्ता रखरखाव",
  "serialNumber": "सीरियल नंबर",
  "pcuNumber": "पीसीयू नंबर",
  "timeZone": "समय क्षेत्र",
  "local": "स्थानीय",
  "pcuQuantity": "पीसीयू मात्रा",
  "state": "राज्य",
  "unlimited_over_delivery": "अनलिमिटेड ओवर डिलीवरी",
  "user": "उपयोगकर्ता",
  "noOfCount": "शिफ्ट",
  "shiftName": "शिफ्ट का नाम",
  "defineDeliveryToleranceIn": "डिलिवरी सहनशीलता",
  "doneQty": "पूरा किया गया मात्रा",
  "releasedQty": "रिलीज़ की गई मात्रा",
  "qtyInQueueOrWork": "क्यू या काम में मात्रा",
  "scrappedQty": "स्क्रैप की गई मात्रा",
  "unreleasedQty": "अविकसित मात्रा",
  "recommendedBuildQtyToReachOrderedQty": "आर्डर की गई मात्रा तक पहुंचने के लिए अनुशंसित निर्माण मात्रा",
  "recommendedBuildQtyToReachMinimumDeliveryQty": "न्यूनतम डिलीवरी मात्रा तक पहुंचने के लिए अनुशंसित निर्माण मात्रा",
  "temperature": "तापमान",
  "material": "सामग्री",
  "cycleTime": "चक्र समय",
  "manufacturedTime": "निर्मित समय",
  "createCycleTime": "चक्र समय बनाएं",
  "materialVersion": "सामग्री संस्करण",
  "update": "अपडेट करें",
  "shiftInterval": "शिफ्ट अंतराल",
  "calendarRules": "कैलेंडर नियम",
  "calendarOverride": "कैलेंडर ओवरराइड",
  "createdOn": "निर्मित किया गया",
  "modifiedOn": "संशोधित किया गया",
  "erpShift": "ईआरपी शिफ्ट",
  "confirm": "पुष्टि करें",
  "alertRow": "क्या आप चयनित पंक्ति के साथ जारी रखना चाहते हैं?",
  "areYouSure": "क्या आप इसे हटाना चाहते हैं",
  "underDeliveryTolerance": "डिलीवरी सहिष्णुता कम",
  "overDeliveryTolerance": "डिलीवरी सहिष्णुता अधिक",
  "maximumDeliveryQty": "अधिकतम डिलीवरी मात्रा",
  "minimumDeliveryQty": "न्यूनतम डिलीवरी मात्रा",
  "addBreak": "ब्रेक जोड़ें",
  "Status": "स्थिति",
  "comment": "टिप्पणी",
  "newStatus": "नयी स्थिति",
  "selectBy": "द्वारा चयन करें",
  "validityShiftInfo": "वैधता/शिफ्ट जानकारी",
  "clockInOutInfo": "क्लॉक-इन/आउट जानकारी",
  "labourInfo": "श्रम जानकारी",
  "action": "क्रिया",
  "day": "दिन",
  "productionDay": "उत्पादन दिन",
  "dayClass": "दिन वर्ग",
  "search": "खोजें",
  "maintenance": "रखरखाव",
  "certification": "प्रमाणन",
  "subStep": "उप-चरण",
  "activityHook": "गतिविधि हुक",
  "operationType": "ऑपरेशन प्रकार",
  "resourceType": "संसाधन प्रकार",
  "defaultOperation": "डिफ़ॉल्ट ऑपरेशन",
  "addAsErpOperation": "ईआरपी ऑपरेशन के रूप में जोड़ें",
  "maxLoopCount": "अधिकतम लूप गिनती",
  "enter": "प्रवेश करें",
  "employeeNumber": "कर्मचारी संख्या",
  "hireDate": "भर्ती तिथि",
  "erpUser": "ईआरपी उपयोगकर्ता",
  "firstName": "पहला नाम",
  "lastName": "अंतिम नाम",
  "emailAddress": "ईमेल पता",
  "erpPersonnelNumber": "ईआरपी कर्मी संख्या",
  "userGroup": "उपयोगकर्ता समूह",
  "labourTracking": "श्रम ट्रैकिंग",
  "supervisor": "पर्यवेक्षक",
  "labourRule": "श्रम नियम",
  "bomType": "बीओएम प्रकार",
  "plannedBom": "योजना बीओएम",
  "plannedRouting": "योजना रूटिंग",
  "lcc": "एलसीसी",
  "plannedWorkCenter": "योजना वर्क सेंटर",
  "orderedQty": "आदेशित मात्रा",
  "priority": "प्राथमिकता",
  "buildQty": "निर्माण मात्रा",
  "erpUom": "ईआरपी यूओएम",
  "plannedStart": "योजना प्रारंभ",
  "plannedCompletion": "योजना समाप्ति",
  "scheduledStart": "अनुसूचित प्रारंभ",
  "scheduledEnd": "अनुसूचित समाप्ति",
  "customerOrder": "ग्राहक आदेश",
  "customer": "ग्राहक",
  "orderType": "आदेश प्रकार",
  "plannedMaterial": "योजना सामग्री",
  "productionQuantities": "उत्पादन मात्रा",
  "materialInwardManagement": "सामग्री आंतरिक प्रबंधन",
  "serialPCU": "सीरियल पीसीयू",
  "enable": "सक्षम करें",
  "bomMaintenance": "बीओएम रखरखाव",
  "bomTemplate": "बीओएम टेम्प्लेट",
  "component": "घटक",
  "assemblyOperation": "असेंबली ऑपरेशन",
  "assemblyQuantity": "असेंबली मात्रा",
  "copyBom": "कॉपी बीओएम",
  "updateBom": "अपडेट बीओएम",
  "assemblySequence": "असेंबली क्रम",
  "componentType": "घटक प्रकार",
  "maxNc": "अधिकतम एनसी",
  "maxUsage": "अधिकतम उपयोग",
  "createBomComponent": "बीओएम घटक बनाएं",
  "createNewBom": "नया बम बनाएं",
  "alternateComponentVersion": "वैकल्पिक घटक संस्करण",
  "designCost": "डिज़ाइन लागत",
  "assySequence": "असेंबली क्रम",
  "componentVersion": "घटक संस्करण",
  "componentDescription": "घटक विवरण",
  "assyQty": "असेंबली मात्रा",
  "assyOperation": "असेंबली ऑपरेशन",
  "assemblyDataTypeBo": "असेंबली डेटा प्रकार ",
  "storageLocationBo": "स्टोरेज लोकेशन ",
  "close": "बंद करें",
  "availableActivities": "उपलब्ध गतिविधियाँ",
  "assignedActivities": "सौंपित गतिविधियाँ",
  "activities": "गतिविधियाँ",
  "activityGroupName": "गतिविधि समूह का नाम",
  "activityGroupMaintenance": "गतिविधि समूह रखरखाव",
  "createActivityGroup": "गतिविधि समूह बनाएं",
  "activityGroupDescription": "गतिविधि समूह विवरण",
  "copyActivityGroup": "कॉपीक्टिविटीग्रुप",
  // ===============================   Next Number     ==============================
  "numbeType": "संख्या प्रकार",
  "definedBy": "परिभाषित किया गया",
  "objectVersion": "वस्तु संस्करण",
  "containerInput": "कंटेनर इनपुट",
  "prefix": "प्रारंभिक",
  "suffix": "उपसर्ग",
  "numberBase": "संख्या आधार",
  "sequenceLength": "क्रम की लंबाई",
  "minSequence": "न्यूनतम क्रम",
  "maxSequence": "अधिकतम क्रम",
  "warningThreshold": "चेतावनी सीमा",
  "incrementBy": "वृद्धि द्वारा",
  "currentSequence": "वर्तमान क्रम",
  "resetSequenceNumber": "क्रम संख्या रीसेट करें",
  "nextNumberActivity": "अगली संख्या गतिविधि",
  "createContinuousSfc": "आयात पर निरंतर एसएफसी बनाएँ",
  "commitNextNumberChangesImmediately": "अगली संख्या परिवर्तनों को तुरंत लागू करें",
  "sampleNextNumber": "नमूना अगली संख्या",
  "nextNumberAppTitle": "अगला नंबर रखरखाव",
  "parametersAndDescription": "पैरामीटर और विवरण",
  "selectItemGroup": "आइटम समूह चुनें",
  "selectDataType": "डेटा प्रकार चुनें",
  "selectBOM": "बीओएम चुनें",
  "selectItem": "आइटम चुनें",
  "retrieve": "प्राप्त करें",
  "selectRouting": "रूटिंग चुनें",
  "rowSelectionMsg": "क्या आप पंक्ति चयन के साथ जारी रखना चाहते हैं?",
  "selectContainer": "कंटेनर चुनें",
  "createNextNumber": "अगली संख्या बनाएँ",

  "podMaintenance": "पॉड रखरखाव",
  "podName": "पॉड नाम",
  "createPodName": "पॉड नाम बनाएं",
  "podLayout": "पॉड लेआउट",
  "kafkaIntegration": "काफ्का इंटीग्रेशन",
  "kafkaId": "काफ्का आईडी",
  "operationCanBeChanged": "ऑपरेशन बदल सकते हैं",
  "resourceCanBeChanged": "संसाधन बदला जा सकता है",
  "showQuantity": "मात्रा दिखाएं",
  "documentName": "दस्तावेज़ का नाम",
  "sessionTimeout": "सत्र समाप्ति",
  "refreshRate": "रिफ्रेश रेट",
  "podType": "पॉड प्रकार",
  "copyPod": "पॉड कॉपी करें",
  "updatePod": "पॉड अपडेट करें",
  "buttonId": "बटन आईडी",
  "buttonLabel": "बटन लेबल",
  "buttonType": "बटन प्रकार",
  "buttons": "बटन",
  "listOptions": "सूची विकल्प",
  "podSelections": "पॉड चयन",
  "printers": "प्रिंटर",
  "home": "होम",
  "buttonSize": "बटन आकार",
  "imageIcon": "छवि आइकन",
  "hotKey": "हॉट की",
  "buttonLocation": "बटन स्थान",
  "podSelection": "पॉड चयन",
  "activitySequence": "गतिविधि अनुक्रम",
  "pluginLocation": "प्लगइन स्थान",
  "clearsPcu": "पीसीयू साफ़ करें",
  "fixed": "फिक्स्ड",
  "createNewPod": "नया पॉड बनाएं",
  "panelLayout": "पैनल लेआउट",
  "selectDefaultOperation": "डिफ़ॉल्ट ऑपरेशन चुनें",
  "selectDefaultResource": "डिफ़ॉल्ट संसाधन चुनें",
  "selectDocumentName": "दस्तावेज़ का नाम चुनें",
  "browseWorkList": "वर्क लिस्ट ब्राउज़ करें",
  "podWorkList": "पॉड वर्क लिस्ट",
  "assembleList": "असेंबल लिस्ट",
  "dcCollectList": "डीसी कलेक्ट लिस्ट",
  "toolList": "टूल लिस्ट",
  "workInstructionList": "वर्क इंस्ट्रक्शन लिस्ट",
  "dcEntryList": "डीसी एंट्री लिस्ट",
  "subStepList": "उप कदम लिस्ट",
  "mainInput": "मुख्य इनपुट",
  "mainInputHotKey": "मुख्य इनपुट हॉट की",
  "infoLine1": "सूचना पंक्ति 1",
  "infoLine2": "सूचना पंक्ति 2",
  "documentPrinter": "दस्तावेज़ प्रिंटर",
  "labelPrinter": "लेबल प्रिंटर",
  "travelerPrinter": "यात्री प्रिंटर",
  "users": "उपयोगकर्ता",
  "userGroupMaintenance": "उपयोगकर्ता समूह प्रबंधन",
  "selectPod": "पॉड का चयन करें",
  "availableUsers": "उपलब्ध उपयोगकर्ता",
  "assignedUsers": "नियुक्त उपयोगकर्ता",
  "availableActivityGroups": "उपलब्ध गतिविधि समूह",
  "assignedActivityGroups": "नियुक्त गतिविधि समूह",



  "pickListManagement": "पिक लिस्ट प्रबंधन",
  "pickListNo": "पिक लिस्ट संख्या",
  "orderNo": "ऑर्डर संख्या",
  "generate": "जनरेट करें",
  "itemCode": "आइटम कोड",
  "itemDescription": "आइटम विवरण",
  "qtyOrdered": "आदेशित मात्रा",
  "qtyPicked": "उठाई गई मात्रा",
  "location": "स्थान",
  "warehouse": "गोदाम",
  "pick": "उठाना",
  "updatePick": "उठाना अपडेट करें",
  "print": "प्रिंट करें",
  "selectOrder": "ऑर्डर चुनें",
  "resourceMaintenance": "संसाधन रखरखाव",
  "createResource": "संसाधन बनाएँ",
  "opcTag": "ओपीसी टैग",
  "processResource": "संसाधन प्रक्रिया",
  "erpEquipmentNumber": "ईआरपी उपकरण संख्या",
  "erpPlantNumber": "ईआरपी संयंत्र संख्या",
  "availableResource": "उपलब्ध संसाधन",
  "assignedResource": "नियुक्त संसाधन",
  "tagName": "टैग नाम",
  "tagUrl": "टैग यूआरएल",
  "identity": "पहचान",
  "selectCertification": "प्रमाणपत्र चुनें",
  "cycleTimeMaintenance": "चक्र समय रखरखाव",
  "dataType": "डेटा प्रकार",
  "manageAlternateComponents": "वैकल्पिक घटकों का प्रबंधन करें",
  "manageParentComponents": "मूल घटकों का प्रबंधन",
  "selectComponent": "घटक चुनें",
  "selectAssemblyOperation": "असेंबली ऑपरेशन चुनें",
  "selectAssemblyDataType": "असेंबली डेटा प्रकार चुनें",
  "selectAlternateComponent": "वैकल्पिक घटक चुनें",
  "selectOperation": "संचालन चुनें",
  "selectMaterial": "सामग्री चुनें",
  "name": "नाम",
  "operationalSettingAppTitle": "ऑपरेशनल सेटिंग",
  "reset": "रीसेट",
  "uomCode": "यूओएम कोड",
  "selectList": "सूची चुनें",
  "list": "सूची",
  "selectPrinters": "प्रिंटर चुनें",
  "deleteMsg": "क्या आप इस अगली संख्या को हटाना चाहते हैं?",
  "parameter": "पैरामीटर",
  "enterFullScreen": "पूर्ण स्क्रीन में जाएं",
  "exitFullScreen": "पूर्ण स्क्रीन से बाहर निकलें",
  "release": "रिहाई",
  "shopOrderRelease": "दुकान आदेश रिहाई",
  "qtyToRelease": "रिहा करने के लिए मात्रा",
  "addToNewProcessLot": "नई प्रक्रिया लॉट में जोड़ें",
  "availableQtyToRelease": "रिहाई के लिए उपलब्ध मात्रा",
  "flowChart": "प्रवाह चार्ट",
  "serialBatchNumber": "सीरियल बैच नंबर",
  "bnoQuantity": "बीएनओ मात्रा",
  "bno": "बीएनओ",
  // ============================ Item Group =====================
  "itemGroupAppTitle": "आइटम समूह रखरखाव",
  "groupDescription": "समूह विवरण",
  "unitPrice": "इकाई मूल्य",
  "groupMember": "समूह सदस्य",
  "createItemGroup": "आइटम समूह बनाएं",
  "itemGroupDeleteMessage": "क्या आप इस आइटम समूह को हटाना चाहते हैं",
  "erpPlantMaintenanceOrder": "ईआरपी प्लांट रखरखाव आदेश",
  "availableResourceTypes": "उपलब्ध संसाधन प्रकार",
  "assignedResourceTypes": "निर्धारित संसाधन प्रकार",
  "copyResource": "संसाधन की कॉपी",

  "selectMethod": "विधि चुनें",
  "method": "विधि",


  //========================List App=========================================
  "allowOperatorToChangeColumnSequence": "ऑपरेटर को कॉलम अनुक्रम बदलने की अनुमति दें",
  "allowOperatorToSortRows": "ऑपरेटर को पंक्तियों को क्रमबद्ध करने की अनुमति दें",
  "allowMultipleSelection": "बहु चयन की अनुमति दें",
  "showAllActiveSfcsToOperator": "ऑपरेटर को सभी सक्रिय एसएफसी दिखाएं",
  "maximumNumberOfRow": "पंक्तियों की अधिकतम संख्या",
  "columnSequence": "अुक्रम",
  "columnName": "कॉलम का नाम",
  "rowSortOrder": "पंक्ति क्रमबद्धता",
  "ShowDetails": "विवरण दिखाएं",
  "width": "चौड़ाई",
  "ascending": "आरोही",
  "descending": "अवरोही",
  "copyList": "प्रति सूची",
  "deleteConfirmation": "हटाने की पुष्टि",
  "ListMaintenance": "सूची रखरखाव",
  "createUserGroup": "उपयोगकर्ता समूह बनाएं",

  "customdataMaintenance": "विशेष डेटा रखरखाव",
  "data field": "डेटा फ़ील्ड",
  "field label": "फ़ील्ड लेबल",
  "required": "आवश्यक",
  "selectdataField": "डेटा फ़ील्ड चुनें",

  // ============================================== DATA FIELD ===========================================
  "dataField": "डेटा फ़ील्ड",
  "fieldLabel": "फ़ील्ड लेबल",
  "dataFieldAppTitle": "डेटा फ़ील्ड रखरखाव",
  "maskGroup": "मास्क समूह",
  "preSaveActivity": "सहेजने से पहले की गतिविधि",
  "isTrackable": "ट्रैक करने योग्य है",
  "qmSelectedSet": "QM चयनित सेट",
  "isMrfRef": "MRF संदर्भ है",
  "browseIcon": "ब्राउज़ आइकन",
  "defaultLabel": "डिफ़ॉल्ट लेबल",
  "fieldValue": "फ़ील्ड मान",
  "labelValue": "लेबल मान",
  "api": "एपीआई",
  "parameters": "पैरामीटर",
  "title": "शीर्षक",
  "editValues": "मान संपादित करें",
  "createDataField": "डेटा फ़ील्ड बनाएं",

  // ============================================== DATA TYPE ===========================================
  "dataTypeAppTitle": "डेटा प्रकार रखरखाव",
  "createDataType": "डेटा प्रकार बनाएं",
  "selectDataField": "डेटा फ़ील्ड चुनें",
  "listDetails": "सूची विवरण",

  "order": "आदेश",
  "componentToScan": "स्कैन करने के लिए घटक",
  "assembled": "असंबद्ध",
  "assemble": "जोड़ें",
  "remaining": "शेष",
  "dataAttribute": "डेटा विशेषता",
  "returnToPod": "POD पर लौटें",
  "confirmCreateDataField": "डेटा फ़ील्ड नहीं मिला, क्या आप इस डेटा फ़ील्ड को बनाना चाहते हैं",

  "attachmentList": "संलग्नक सूची", // Hindi


  // ============================================= DC PLUGIN ===========================================
  "parameterList": "पैरामीटर सूची",
  "showDetails": "विवरण दिखाएँ",
  "collectData": "डेटा एकत्र करें",
  "saveDraft": "ड्राफ्ट सहेजें",
  "submit": "जमा करें",
  "dataFieldList": "डेटा फ़ील्ड सूची",
  "collectedDCParameterList": "एकत्रित डीसी पैरामीटर सूची",
  "returnToDCList": "डीसी सूची पर लौटें",
  "range": "रेंज",
  "dateTime": "तारीख और समय",
  "collectionMethod": "संग्रह विधि",
  "parameterName": "पैरामीटर नाम",
  "collectDataAt": "डेटा एकत्र करें",

  // =============================================== WORK INSTRUCTION ======================================
  "textInstruction": "पाठ निर्देश", // Hindi
  "urlInstruction": "यूआरएल निर्देश",
  "instructionType": "निर्देश प्रकार",
  "WorkInstruction_Description": "विवरण",
  "WorkInstructionID_Revision": "कार्य निर्देश / संशोधन",
  "Operation_StepId": "ऑपरेशन चरण आईडी",
  "StepId": "चरण आईडी",



  "workInstructionMaintenance": "कार्य निर्देश रखरखाव",
  "workInstruction": "कार्य निर्देश",
  "createWorkInstruction": "कार्य निर्देश बनाएँ",
  "alwaysShowInNewWindow": "हमेशा नई विंडो में दिखाएं",
  "logViewing": "लॉग देखना",
  "changeAlert": "अलर्ट बदलें",
  "erpWi": "ERP कार्य निर्देश",
  "text": "पाठ",
  "url": "यूआरएल",
  "file": "फाइल",

  // ================================== SCRAP AND USER =======================
  "pcu/shopOrder/processLot": "पीसीयू / शॉप ऑर्डर / प्रोसेस लॉट",
  "comments": "टिप्पणियाँ",
  "scrap": "स्क्रैप",
  "unscrap": "स्क्रैप रद्द",
  "Scrap": "स्क्रैप",
  "Unscrap": "���्क्रैप रद्द",
  "scrapUnscrapTitle": "स्क्रैप प्रबंधन",
  "confirmPassword": "पासवर्ड की पुष्टि करें",
  "password": "पासवर्ड",
  "selectSites": "साइट चुनें",
  "PCU": "पीसीयू",
  "Shop Order": "शॉप ऑर्डर",
  "Process Lot": "प्रोसेस लॉट",
  "workflowIntegrationMaintenance": "कार्य प्रवाह एकीकरण रखरखाव",
  "workflowIntegration": "कार्य प्रवाह एकीकरण",
  "createWorkflowIntegration": "कार्य प्रवाह एकीकरण बनाएँ",
  "identifier": "पहचानकर्ता",
  "messageId": "संदेश आईड",
  "processBy": "वारा प्रक्रिया करें",
  "jsonTransformationType": "JSON रूपांतरण प्रकार",
  "preProcessJolt": "पूर्व-प्रक्रिया झटका",
  "preProcessApi": "पूर्व-प्रक्रिया API",
  "serviceApi": "सेवा API",
  "expectedSplits": "अपेक्षित विभाजन",
  "postProcessJolt": "पोस्ट-प्रक्रिया झटका",
  "postProcessApi": "पोस्ट-प्रक्रिया",
  "passHandler": "पास हैंडलर",
  "failHandler": "फेल हैंडलर",
  "processTransformation": "प्रक्रिया रूपांतरण",
  // ============================================== Jolt Spec ===========================================
  "specName": "स्पेक नाम",
  "specNamePlaceholder": "स्पेक नाम दर्ज करें",
  "specNameRequired": "कृपया स्पेक नाम दर्ज करें!",
  "typePlaceholder": "प्रकार चुनें",
  "typeRequired": "कृपया प्रकार चुनें!",
  "joltSpec": "जोल्ट स्पेक",
  "joltSpecPlaceholder": "जोल्ट विवरण दर्ज करें",
  "xsltSpec": "XSLT स्पेक",
  "xsltSpecPlaceholder": "XSLT विवरण दर्ज करें",
  "encodeXsltSpec": "एनकोड XSLT स्पेक",
  "encodeXsltSpecPlaceholder": "एनकोड किा गया XSLT विवरण दर्ज करें",
  "jsonAta": "JsonAta स्पेक",
  "jsonAtaPlaceholder": "JsonAta विवरण दर्ज करें",
  "encodedJsonAtaSpec": "एनकोड किया गया JsonAta स्पेक",
  "encodedJsonAtaSpecPlaceholder": "एनकोड किया गया JsonAta विवरण दर्ज करें",

  "joltAppTitle": "जोल्ट स्पेक रखरखाव",
  "createSpec": "स्पेक बनाएं",
  "encode": "एनकोड",
  "decode": "डीकोड",
  "spec": "स्पेक",
  "decodeXsltSpec": "डीकोड की गई XSLT विशिष्टता",
  "decodeJsonAtaSpec": "डीकोड की गई JsonAta विशिष्टता",

  // Added translations
  "entityType": "इकाई प्रकार",
  "entityName": "इकाई नाम",
  "eventIntervalSeconds": "घटना अंतराल सेकंड",
  "cronExpression": "क्रॉन एक्सप्रेशन",
  "edit": "संपादित करें",
  "runJob": "कार्य चलाएं",
  "stopScheduler": "शेड्यूलर रोकें",
  "machineStatusChange": "मशीन स्थिति परिवर्तन",

  "apiToProcess": "प्रक्रिया के लिए एपीआई",
  "selectPreProcessJolt": "प्री-प्रोसेस जॉल्ट चुनें",
  "selectPostProcessJolt": "पोस्ट-प्रोसेस जॉल्ट चुनें",
  "selectPreProcessXSLT": "प्री-प्रोसेस XSLT चुनें",
  "processJoltXslt": "जॉल्ट XSLT प्रक्रिया",
  "splitConfigurations": "विभाजन विन्यास",
  "splitIdentifier": "विभाजन पहचानकर्ता",
  "conditional": "सशर्त",
  "parallel": "समानांतर",
  "anyOrder": "कोई भी क्रम",
  "orderNumber": "आदेश संख्या",
  "recipeVersion": "रेसिपी संस्करण",
  "recipeNo": "रेसिपी नंबर",
  "targetQuantity": "लक्षित मात्रा",
  "startDate": "प्रारंभ तिथि",
  "finishDate": "समाप्ति तिथि",
  "schedFinTime": "निर्धारित समाप्ति समय",
  "schedStartTime": "निर्धारित प्रारंभ समय",
  "selectRecipeNo": "रेसिपी नंबर चुनें",
  "batchNumber": "बैच संख्या",
  "batchNumberQuantity": "बैच संख्या मात्रा",

  // ============================================== Process Order Plugin ===========================================
  "complete": "पूर्ण",
  "start": "शुरू",

  // ============================================== NC Group ===========================================
  "ncGroups": "NC समूह",
  "ncGroup": "NC समूह",
  "ncCode": "NC कोड",
  "ncGroupAppTitle": "NC समूह रखरखाव",
  "ncGroupFilterPriority": "NC समूह फ़िल्टर प्राथमिकता",
  "validAtAllOperations": "सभी संचालनों में मान्य",
  "parameterBo": "पैरामीटर बीओ",
  "operationBO": "ऑपरेशन बीओ",
  "dcGroupBO": "डीसी समूह बीओ",
  "pcuBO": "पीसीयू बीओ",
  "testDateTime": "परीक्षण दिनांक और समय",
  "dcGroupDescription": "डीसी समूह विवरण",
  "subStepID": "उप-चरण आईडी",
  "measureStatus": "माप स्थिति",
  "measureType": "माप प्रकार",
  "unitOfMeasure": "माप की इकाई",
  "highLimit": "उच्च सीमा",
  "lowLimit": "निम्न सीमा",
  "expected": "अपेक्षित",
  "actualNum": "वास्तविक संख्या",
  "dcComment": "डीसी टिप्पणी",
  "usedLimitSeq": "प्रयुक्त सीमा क्रम",
  "elapsedTime": "व्यतीत समय",
  "originalActual": "मूल वास्तविक",
  "originalDcComment": "मूल डीसी टिप्पणी",
  "originalTestDateTime": "मूल परीक्षण दिनांक और समय",
  "edited": "संपादित",
  "editedUserBO": "संपादित उपयोगकर्ता बीओ",
  "editedDateTime": "संपादित दिनांक और समय",
  "internalMeasureID": "आंतरिक माप आईडी",
  "routingBO": "रूटिंग बीओ",
  "stepID": "चरण आईडी",
  "userBO": "उपयोगकर्ता बीओ",
  "overrideUserBO": "ओवरराइड उपयोगकर्ता बीओ",
  "dcGroupVersion": "डीसी समूह संस्करण",
  "detailInformation": "विस्तृत जानकारी",
  "erpSent": "ईआरपी भेजा गया",
  "qmAccepted": "क्यूएम स्वीकृत",
  "detail": "विवरण",
  "dcGroup": "डीसी समूह",
  "viewPdf": "पीडीएफ देखें",
  "availableNCCodes": "उपलब्ध एनसी कोड",
  "assignNCCodes": "एनसी कोड सौंपें",
  "ncGroupDeleteMessage": "क्या आप इस एनसी समूह को हटाना चाहते हैं",
  "ncCodeDPMOCategory": "एनसी कोड डीपीएमओ श्रेणी",
  "operationList": "ऑपरेशन सूची",
  "createNCGroup": "एनसी समूह बनाएँ",
  "assignedNC": "एस्क्वाइज्ड एनसी",
  "availableNC": "उपलब्ध एनसी",
  "logNc": "लॉग एनसी",
  "done": "पूर्ण",
  "NcCodeMaintenance": "एनसी कोड मेंटेनेंस",
  "NC Code": "एनसी कोड",
  "operationGroups": "ऑपरेशन ग्रुप्स",
  "dispositionRoutings": "डिस्पोज़िशन रूटिंग्स",
  "NC Groups": "एनसी ग्रुप्स",
  "secondaries": "सेकंडरीज़",
  "createNcCode": "एनसी कोड बनाएं",
  "assignNCtoComponent": "एनसी को कंपोनेंट से असाइन करें",
  "ncCategory": "एनसी श्रेणी",
  "dpmoCategory": "डीपीएमओ श्रेणी",
  "ncDatatype": "एनसी डेटा प्रकार",
  "collectRequiredNCDataonNC": "एनसी पर आवश्यक डेटा एकत्र करें",
  "ncPriority": "एनसी प्राथमिकता",
  "maximumNCLimit": "अधिकतम एनसी सीमा",
  "ncSeverity": "एनसी गंभीरता",
  "secondaryCodeSpecialInstruction": "सेकंडरी कोड विशेष निर्देश",
  "canBePrimaryCode": "प्राथमिक कोड हो सकता है",
  "closureRequired": "समापन आवश्यक",
  "autoClosePrimaryNC": "प्राथमिक एनसी स्वचालित रूप से बंद करें",
  "autoCloseIncident": "घटना स्वचालित रूप से बंद करें",
  "secondaryRequiredForClosure": "समापन के लिए सेकंडरी आवश्यक",
  "erpQNCode": "ईआरपी क्यूएन कोड",
  "erpCatalog": "ईआरपी कैटलॉग",
  "erpCodeGroup": "ईआरपी कोड समूह",
  "erpCode": "ईआरपी कोड",
  "oeeQualityKPIRelevant": "ओईई गुणवत्ता केपीआई संबंधित",
  "selectNcDatatype": "एनसी डेटा प्रकार चुनें",
  "validOperations": "मान्य ऑपरेशन",
  "dispositionGroups": "डिस्पोज़िशन ग्रुप्स",
  "availableRouting": "उपलब्ध रूटिंग",
  "assignedRouting": "असाइन की गई रूटिंग",
  "availableSecondaries": "उपलब्ध सेकंडरीज़",
  "assignedSecondaries": "असाइन की गई सेकंडरीज़",
  "availableNcGroups": "उपलब्ध एनसी समूह",
  "assignedNcGroups": "असाइन किए गए एनसी समूह",
  "copyNcCode": "एनसी कोड कॉपी करें",
  "toolNumberMaintenance": "उपकरण संख्या रखरखाव",
  "toolNumber": "उपकरण संख्या",
  "toolGroup": "उपकरण समूह",
  "qtyAvailable": "उपलब्ध मात्रा",
  "erpPlanMaintenanceOrder": "ईआरपी योजना रखरखाव आदेश",
  "toolQty": "उपकरण मात्रा",
  "createToolNumber": "उपकरण संख्या बनाएँ",
  "calibration": "कैलिब्रेशन",
  "measurementPoints": "मापन बिंदु",
  "measurementPoint": "मापन बिंदु",
  "calibrationType": "कैलिब्रेशन प्रकार",
  "calibrationPeriod": "कैलिब्रेशन अवधि",
  "calibrationCount": "कैलिब्रेशन संख्या",
  "maximumCalibrationCount": "अधिकतम कैलिब्रेशन संख्या",
  "expirationDate": "समाप्ति तिथि",
  "displayClosedNc": "बंद एनसी प्रदर्शित करें",
  "selectRoute": "रूटिंग चुनें",
  "customOrder": "कस्टम ऑर्डर",
  "createToolGroup": "टूल समूह बनाएं",
  "timeBased": "समय आधारित",
  "quantityRequired": "आवश्यक मात्रा",
  "erpGroup": "ERP समूह",
  "itemVersion": "आइटम संस्करण",
  "trackingControl": "ट्रैकिंग कंट्रोल",
  "toolGroupMaintenance": "टूल समूह रखरखाव",
  "listConfiguration": "पट्टी व्यवस्थापन",
  "multiProcessOrderRelease": "एकाधिक प्रक्रिया आदेश उत्सर्ग",
  "multiProcessOrder": "एकाधिक प्रक्रिया आदेश",
  "phase": "चरण",
  "mrpController": "MRP नियंत्रक",
  "productionScheduler": "उत्पादन शेड्यूलर",
  "reservationNumber": "रिजर्वेशन नंबर",
  "productionStartDate": "उत्पादन शुरू होने की तिथि",
  "productionFinishDate": "उत्पादन समाप्त होने की तिथि",
  "actualStartDate": "वास्तविक शुरू होने की तिथि",
  "actualFinishDate": "वास्तविक समाप्त होने की तिथि",
  "inUse": "बहुविध उपयोग किया गया",
  "measuredUom": "मापी इकाई",
  "entryPhase": "प्रवेश चरण",
  "exitPhase": "निकासी चरण",
  "entryOperation": "प्रवेश संचालन",
  "lastOperationAtPhase": "अंतिम संचालन",
  "nextPhase": "अगला चरण",

  "accept": "स्वीकृत",
  "partial": "आंशिक",
  "skip": "निर्गमित",
  "buyOff": "खरीद अवधि",
  "username": "उपयोगकर्ता नाम",
  "userAuthentication": "उपयोगकर्ता प्रमाणीकरण",
  "login": "लॉग इन",
  // ======================================= Certification Maintenance ===========================================
  "certificationmaintenance": "प्रमाणन रखरखाव",
  "certifications": "प्रमाणपत्र",
  "createCertification": "प्रमाणपत्र बनाएं",
  "durationType": "अवधि प्रकार",
  "maxNumberOfExtensions": "विस्तार की अधिकतम संख्या",
  "maxExtensionDuration": "अधिकतम विस्तार अवधि",
  "assignment": "असाइनमेंट",
  "availableUserGroups": "उपलब्ध उपयोगकर्ता समूह",
  "assignedUserGroups": "असाइन किए गए उपयोगकर्ता समूह",
  "measurementpoints": "मापन बिंदु",
  "copyCertification": "प्रमाणपत्र कॉपी करें",
  "activityId": "गतिविधि आईडी",
  "selectPcu": "पीसीयू चुनें",
  "selectBatchNo": "बैच नंबर चुनें",
  "createPodMaintenance": "पीओडी रखरखाव बनाएं",
  "reloadWorkList": "कार्य सूची फिर से लोड करें",
  "reloadResource": "संसाधन फिर से लोड करें",
  "settings": "सेटिंग्स",
  "layout": "लेआउट",
  "PCUOrBatchNumberBrowseActivity": "पीसीयू या बैच नंबर ब्राउज गतिविधि",
  "PodWorkListActivity": "पीओडी कार्य सूची गतिविधि",
  "trackOee": "ओईई ट्रैक करें",
  "ButtonActivityInWork": "कार्य गतिविधि",
  "ButtonActivityInQueue": "क्रम गतिविधि",
  "OnTabOutOfOperation": "ऑपरेशन से बाहर",
  "OnTabOutOfWorkcenter": "वर्कसेंटर से बाहर",
  "OnTabOutOfResource": "संसाधन से बाहर",
  "UpdateFieldsToSession": "सत्र में फ़ील्ड अपडेट करें",
  "scrapQuantity": "स्क्रैप मात्रा",
  "subPod": "उप पीओडी",
  "podCategory": "पीओडी श्रेणी",
  "buttonActivityInQueue": "क्रम गतिविधि",
  "buttonActivityInWork": "कार्य गतिविधि",
  "activityDescription": "गतिविधि विवरण",
  "panel": "पैनल",
  "defaultPlugin": "डिफ़ॉल्ट प्लगइन",
  "otherPlugin": "अन्य प्लगइन",
  "workListPanel": "कार्य सूची पैनल",
    // ============================================== Line Clearance ===========================================
  "lineClearanceMaintenance": "लाइन क्लियरेंस रखरखाव",
  "lineClearance": "लाइन क्लियरेंस",
  "templateName": "टेम्पलेट नाम",
  "clearanceTimeLimit": "क्लियरेंस समय सीमा",
  "maxPendingTasks": "अधिकतम लंबित कार्य",
  "clearanceReminderInterval": "क्लियरेंस रिमाइंडर अंतराल",
  "notifyOnCompletion": "पूर्णता पर सूचित करें",
  "enablePhotoEvidence": "फोटो प्रमाण सक्षम करें",
  "associated": "संबद्ध",
  "workcenterId": "वर्कसेंटर आईडी",
  "resourceName": "संसाधन नाम",
  "createLineClearance": "लाइन क्लियरेंस बनाएं",
  "taskid": "कार्य आईडी",
  "taskname": "कार्य नाम",
  "mandatory": "अनिवार्य",
  "evidencerequired": "प्रमाण आवश्यक",
  "userRoles": "उपयोगकर्ता भूमिकाएं",
  "userid": "उपयोगकर्ता आईडी",
  "permissions": "अनुमतियां",
  "selectUser": "उपयोगकर्ता चुनें",
  "tasks": "कार्य",
  "uomConversion": "यूओएम रूपांतरण",
  "conversion": "रूपांतरण",
  "materialCountConversion": "माल काउंट रूपांतरण",
  "convertUom": "यूओएम रूपांतरण",
  "count": "गिनती",
  "conversionDeleteMessage": "क्या आप इस रूपांतरण को हटाना चाहते हैं?",
  "baseAmt": "आधार राशि",
  "conversionItem": "रूपांतरण आइटम",
  

  "areYouSureDeleteThisSplit": "क्या आप इस विभाजन को हटाना चाहते हैं?",
  "attach": "वापस लाना",
  "filePreview": "फ़ाइल पूर्वावलोकन",
  "change": "बदलना",
  "preview": "पूर्वावलोकन",
  "defaultPhaseId": "डिफ़ॉल्ट चरण आईडी",
  "reloadSiteConfirmation": "क्या आप इस साइट को फिर से लोड करना चाहते हैं?",
  "phaseCanBeChanged": "चरण बदल सकते हैं",
  "auditLogReport": "ऑडिट लॉग रिपोर्ट",
  "dataCollectionReport": "डेटा कलेक्शन रिपोर्ट",
  "dataCollectionGraph": "डेटा कलेक्शन ग्राफ",
  "showResource": "संसाधन दिखाएं",
  "showOperation": "संचालन दिखाएं",
  "showPhase": "चरण दिखाएं",
  "selectCategory": "श्रेणी चुनें",
  "currentSetting": "वर्तमान सेटिंग",
  "date/time": "दिनांक/समय",
  "changeType": "परिवर्तन प्रकार",
  "dateRange": "दिनांक सीमा",
  "time": "समय",
  "topicConfiguration": "टोपिक कॉन्फिगरेशन",
  "createTopicConfiguration": "टोपिक कॉन्फिगरेशन बनाएं",
  "topicName": "टोपिक नाम",
  "apiUrl": "एपीआई यूआरएल",

  "taskDescription": "कार्य विवरण",
  "evidence": "प्रमाण",
  "startedDateTime": "शुरू होने की तिथि",
  "completedDateTime": "समाप्त होने की तिथि",
  "reason": "कारण",
  "approved": "स्वीकृत",
  "approvedDateTime": "स्वीकृत दिनांक और समय",
  "approvedBy": "स्वीकृत द्वारा",
  "rejectedDateTime": "अस्वीकृत दिनांक और समय",
  "rejectedBy": "अस्वीकृत द्वारा",
  "updatedDateTime": "अपडेट दिनांक और समय",
  "updatedBy": "अपडेट द्वारा",
  "startedBy": "शुरू होने के द्वारा",
  "completedBy": "समाप्त होने के द्वारा",
  "taskName": "कार्य नाम",
  "isMandatory": "अनिवार्य",
  "evidenceRequired": "प्रमाण आवश्यक",
  "theme": "थीम",
  "cycleTime(sec)": "कालक्रम समय (सेकंड)",

  "shiftStart": "शिफ्ट स्टार्ट",
  "shiftEnd": "शिफ्ट एंड",
  "shiftAvailableTime": "शिफ्ट उपलब्ध समय",
  "totalBreakHours": "कुल ब्रेक घंटे",
  "createdDatetime": "बनाया गया दिनांक और समय",
  "updatedDatetime": "अपडेट दिनांक और समय",
  "createdBy": "बनाया गया द्वारा",
  "eventData": "घटना डेटा",
  "plant": "फुलावा",
  "eventType": "घटना प्रकार",
  "buyOffAction": "खरीद अवधि क्रिया",
  "history": "इतिहास",
  "endDate": "अंतिम तिथि",
  "selectSite": "साइट चुनें",
  "downtimeType": "डाउनटाइम प्रकार",
  "selectStatus": "स्थिति चुनें",
  "selectNewStatus": "नया स्थिति चुनें",
  "selectBatchNumber": "बैच नंबर चुनें",
  "selectOrderNumber": "आदेश नंबर चुनें",
  "batchStepStatus": "बैच चरण स्थिति",
  "batchStartedTime": "बैच शुरू होने की तिथि",
  "batchCompletedTime": "बैच समाप्त होने की तिथि",
  "approval": "स्वीकृत",
  "PhaseId": "चरण आईडी",
  "InQueueQty": "क्रम में मात्रा",
  "InWorkQty": "कार्य में मात्रा",
  "CompleteQty": "पूर्ण करने की मात्रा",
  "ScrapQty": "स्क्रैप मात्रा",
  "level": "स्तर",
  "message": "संदेश",


  "activityHookId": "एक्टिविटी हुक आईडी",
  "targetClass": "लक्ष्य क्लास",
  "targetMethod": "लक्ष्य विधि",
  "hookType": "हुक प्रकार",
  "hookClass": "हुक क्लास",
  "hookMethod": "हुक विधि",
  "executionMode": "निष्पादन मोड",
  "logo": "लोगो",
  "background": "बैकग्राउंड",
  "color": "रंग",
  "lineColor": "वरिया रंग",

  "plannedCycleTime": "योजना कालक्रम समय",
  "actualCycleTime": "वास्तविक कालक्रम समय",
  "totalBreakInMinutes": "कुल ब्रेक (मिनट)",

 
  "serviceExtension": "सेवा विस्तार",
  "createServiceExtension": "सेवा विस्तार बनाएं",
  "createExtension": "विस्तार बनाएं",
  "serviceExtensionAppTitle": "सेवा विस्तार रखरखाव",
  "selectResourceType": "संसाधन प्रकार चुनें",
  "executionPointId": "निष्पादन बिंदु आईडी",
  "extensionDeleteMessage": "क्या आप इस एक्सटेंशन को हटाना चाहते हैं?",
  "executionPoint": "निष्पादन बिंदु",
  "extensionActivity": "विस्तार गतिविधि",
  "MaterialDescription": "माल विवरण",
  "releaseTime": "उत्सर्जन समय",
  "unitOfMeasurement": "यूनिट में मापन",
  "releaseOrder": "उत्पादन आदेश",
  "createdDateTime": "बनाया गया दिनांक और समय",
  "releaseQty": "उत्सर्जन मात्रा",
  "productionTime": "उत्पादन समय",  
 'productCode' : 'उत्पाद कोड',
 'productName': 'उत्पाद नाम',
 'downloadDate' : 'डाउनलोड तिथि',
 'batchStatus': 'बैच स्थिति',

 "createConfiguration": "कॉन्फ़िगरेशन बनाएं",
  "apiConfiguration": "एपीआई कॉन्फ़िगरेशन",
  "storedProcedure": "स्टोर की गई प्रक्रिया",
  "httpMethod": "HTTP विधि",
  "inputParameters": "इनपुट पैरामीटर",
  "outputStructure": "आउटपुट संरचना",
  "apiName": "एपीआई नाम",
  "deleteApiConfigMessage": "क्या आप इस कॉन्फ़िगरेशन को हटाना चाहते हैं",
  "apiConfigMaintenance": "एपीआई कॉन्फ़िगरेशन रखरखाव",
  "configuration": "कॉन्फ़िगरेशन",

  "shiftId": "शिफ्ट आईडी",
  "selectShift": "शिफ्ट चुनें",

  "productGroup":"उत्पाद समूह",
  "selectProductGroup":"उत्पाद समूह चुनें",

  "componentBuilderMaintenance": "कम्पोनेंट बिल्डर रखरखाव",
  "validation": "प्रमाणीकरण",
  "defaultValue": "डिफ़ॉल्ट मान",
  "componentLabel": "कम्पोनेंट लेबल",
  "createComponent": "कम्पोनेंट बनाएं",
  "dropdownOptions": "ड्रॉपडाउन विकल्प",
  "addOption": "विकल्प जोड़ें",
  "noOfColumns": "स्तंभों की संख्या",
  "noOfRows": "पंक्तियों की संख्या",
  "resourceDetails": "संसाधन विवरण",


  "workflowStates": "कार्यप्रवाह अवस्थाएँ",
  "states": "अवस्थाएँ",
  "editableFields": "संपादन योग्य फ़ील्ड्स",
  "appliesTo": "लागू होता है",
  "isActive": "सक्रिय है",
  "isEnd": "अंतिम है",
  "createState": "अवस्था बनाएं",
  "workflowStatesMaster": "कार्यप्रवाह अवस्था मास्टर",
}