export const kannadaLanguage = {
  "schedulerMaintenance": "ಅನೂಕುಲನೆ ನಿರ್ವಹಣೆ",
  "max": "ಗರಿಷ್ಠ",
  "min": "ಕಿಮ್ಮತ್ತು",
  "tolerance": "ಅನುಮತಿ",
  "actualValue": "ವಾಸ್ತವ ಮೌಲ್ಯ",
  "actionsOnFailure": "ವಿಫಲವಾದಾಗ ಚಟುವಟಿಕೆಗಳು",
  "monitoringFrequency": "ನಿಗಾ ಅವೃತ್ತಿ",
  "expectedValue": "ಅನುಮಾನಿತ ಮೌಲ್ಯ",
  "qcId": "ಕ್ಯೂಸೀ ಐಡಿ",
  "expectedValueRange_kn": "ಅನುಮಾನದ ಮೌಲ್ಯ ವ್ಯಾಪ್ತಿ",
  "frequency": "ಆವೃತ್ತಿ",
  "dataPointID": "ದತ್ತೆ ಪಾಯಿಂಟ್ ಐಡಿ",
  "pressure": "ಊರ್ಜೆ",
  "duration": "ಅವಧಿ",
  "rpm": "ಆರ್ಎಂಪಿ",
  "workCenterId": "ಕೋಶ ಐಡಿ",
  "defaultPhaseId": "ಡೀಫಾಲ್ಟ್ ಹಂತ ಐಡಿ",
  "resourceId": "ಸಂಪತ್ತು ಐಡಿ",
  "adjustments": "ಸಂಯೋಜನೆಗಳು",
  "qualityControlParameters": "ಗುಣಮಟ್ಟದ ನಿಯಂತ್ರಣ ಪರಿಮಾಣಗಳು",
  "dataCollection": "ದತ್ತೆ ಸಂಗ್ರಹಣೆ",
  "resources": "ಸಂಪತ್ತುಗಳು",
  "tools": "ತಂಡಗಳು",
  "safetyProcedures": "ಭದ್ರತಾ ವಿಧಾನಗಳು",
  "yieldWasteTracking": "ಫಲಿತಾಂಶ ಮತ್ತು ತ್ಯಾಜ್ಯ ನಿಗಾ",
  "triggerPoints": "ಟ್ರಿಗರ್ ಪಾಯಿಂಟ್‌ಗಳು",
  "packagingLabeling": "ಪ್ಯಾಕೇಜಿಂಗ್ ಲೇಬ್ಲಿಂಗ್",
  "recipeName": "ಬಡಲೆ",
  "ccp": "ಸಿಸಿಪಿ",
  "stepName": "ಹಂತದ ಹೆಸರು",
  "instruction": "ಸೂಚನೆ",
  "steps": "ಹಂತಗಳು",
  "id": "ಐಡಿ",
  "associatedStep": "ಸಂಬಂದಿಸಿದ ಹಂತ",
  "expectedCycleTime": "ಅನುಮಾನದ ಚಕ್ರಕಾಲ",
  "ingredients": "ಪದಾರ್ಥಗಳು",
  "phases": "ಹಂತಗಳು",
  "phaseId": "ಹಂತದ ಐಡಿ",
  "phaseName": "ಹಂತದ ಹೆಸರು",
  "phasesName": "ಹಂತಗಳ ಹೆಸರುಗಳು",
  "inactive": "ನಿಷ್ಕ್ರಿಯ",
  "recipeId": "ಪಾಕವಿಧಾನ ಐಡಿ",
  "batchSize": "ಕಣದ ಗಾತ್ರ",
  "batchUom": "ಕಣದ ಏಕಕ",
  "totalExpectedCycleTime": "ಒಟ್ಟು ನಿರೀಕ್ಷಿತ ಚಕ್ರ ಸಮಯ",
  "totalActualCycleTime": "ಒಟ್ಟು ವಾಸ್ತವಿಕ ಚಕ್ರ ಸಮಯ",
  "active": "ಸಕ್ರಿಯ",
  "recipeStepDetails": "ವಿಧಾನ ಹಂತದ ವಿವರಗಳು",
  "workInstructions": "ಕಾರ್ಯ ಸೂಚನೆಗಳು",
  "dataCollections": "ದತ್ತಾಂಶ ಸಂಗ್ರಹಣೆ",
  "parameterLists": "ಪರಿಮಾಣ ಪಟ್ಟಿ",
  "classification": "ವರ್ಗೀಕರಣ",
  "relaxedRecipeFlow": "ಶ್ರೇಣೀಬದ್ಧವಾದ ವಿಧಾನ",
  "scan": "ಸ್ಕಾನ್",
  "shipmentOrderNumber": "ಕಳುಹಿಸುವ ಆದೇಶ ಸಂಖ್ಯೆ",
  "dispatchDetails": "ವಿತರಣೆಯ ವಿವರಗಳು",
  "dispatchDateTime": "ವಿತರಣೆಯ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "recipientInfo": "ಸ್ವೀಕೃತ್ತ ಮಾಹಿತಿ",
  "dispatchInfo": "ವಿತರಣೆಯ ಮಾಹಿತಿ",
  "recipeSteps": "ವಿಧಾನ ಹಂತಗಳು",
  "stageType": "ಹಂತ ಪ್ರಕಾರ",
  "recipeType": "ಬಳಕೆ ಪ್ರಕಾರ",
  "recipe": "ಬಳಕೆ",
  "stage": "ಹರವು",
  "processOrderRelease": "ಪ್ರಕ್ರಿಯೆ ಬಿಡುಗಡೆ",
  releaseProcessOrder: "ವಿಮೋಚನ ಪ್ರಕ್ರಿಯೆ ಆರ್ಡರ್",
  processOrder: "ಪ್ರಕ್ರಿಯೆ ಆರ್ಡರ್",
  appTitle: "ಐಟಂ ನಿರ್ವಹಣೆ",
  item: "ಐಟಂ",
  shiftName: "ಶಿಫ್ಟ್ ಹೆಸರು",
  description: "ವಿವರಣೆ",
  recipeDescription: "ವಿವರಣೆ",
  searchActivities: "ಚಟುವಟಿಕೆಗಳನ್ನು ಹುಡುಕಿ",
  logout: "ಲಾಗ್ ಔಟ್",
  revision: "ಪರಿಷ್ಕರಣೆ",
  "qtyConsumed": "ಖರೀದಿಸಿದ ಪ್ರಮಾಣ",
  status: "ಸ್ಥಿತಿ",
  procurementType: "ಸಂಗ್ರಹಣೆ ಪ್ರಕಾರ",
  lotSize: "ಸಾಕಷ್ಟು ಗಾತ್ರ",
  createShift: "ಶಿಫ್ಟ್ ರಚಿಸು",
  "data": "ಡೇಟಾ",
  workCenter: "ಕೆಲಸ ಕೇಂದ್ರ",
  resource: "ಸಾಧನ",
  add: "ಜೋಡಿಸು",
  main: "ಪ್ರಮುಖ",
  alternateComponent: "ಪರ್ಯಾಯ ಘಟಕ",
  printDocument: "ಮುದ್ರಣ ದಾಖಲೆ",
  customData: "ಕಸ್ಟಮ್ ಡೇಟಾ",
  itemGroup: "ಐಟಂ ಗುಂಪು",
  qtyRestriction: "ಪ್ರಮಾಣದ ನಿರ್ಬಂಧ",
  routing: "ರೌಟಿಂಗ್",
  routingVersion: "ರೌಟಿಂಗ್ ಆವೃತ್ತಿ",
  bom: "ಬಿಒಎಂ",
  bomVersion: "ಬಿಒಎಂ ಆವೃತ್ತಿ",
  assemblyDataType: "ವಿಧಾನ ಪ್ರಕಾರ",
  removalDataType: "ತೆಗೆಯುವ ಪ್ರಕಾರ",
  receiptDataType: "ಸ್ವೀಕೃತ ಪ್ರಕಾರ",
  currentVersion: "ಪ್ರಸ್ತುತ ಆವೃತ್ತಿ",
  itemType: "ಐಟಂ ಪ್ರಕಾರ",
  create: "ರಚಿಸಿ",
  save: "ಉಳಿಸಿ",
  cancel: "ರದ್ದುಮಾಡಿ",
  "sequence": "ಕ್ರಮಾಂಕ",
  "version": "ಆವೃತ್ತಿ",
  "versions": "ಆವೃತ್ತಿ: ",
  "parentMaterial": "ಪೋಷಕ ವಸ್ತು",
  "validFrom": "ಇಂದೆ ಮಾನ್ಯ",
  "validTo": "ಇಲ್ಲಿಯವರೆಗೆ ಮಾನ್ಯ",
  "createdDate": "ತಯಾರಿಸಿದ ದಿನಾಂಕ: ",
  "modifiedTime": "ಮಾರ್ಪಡಿಸಿದ ಸಮಯ: ",
  "availableDocuments": "ಲಭ್ಯವಿರುವ ದಾಖಲೆಗಳು",
  "assignedDocuments": "ನಿಯೋಜಿತ ದಾಖಲೆಗಳು",
  "document": "ದಾಖಲೆ",
  "createItem": "ಐಟಂ ರಚಿಸಿ",
  "value": "ಮೌಲ್ಯ",
  "go": "ಹೋಗು",
  copy: "ಪ್ರತಿ",
  confirmCopy: "ದೃಢೀಕರಿಸು ಪ್ರತಿ",
  delete: "ಅಳಿಸಿ",
  confirmDelete: "ಅಳಿಸುವುದು ದೃಢೀಕರಿಸಿ",
  deleteMessage: "ನೀವು ಈ ಐಟಂ ಅನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುತ್ತೀರಾ?",
  "insert": "ಸೇರಿಸು",
  "removeSelected": "ಆಯ್ದವುಗಳನ್ನು ತೆಗೆದುಹಾಕಿ",
  "removeAll": "ಎಲ್ಲವನ್ನು ತೆಗೆದುಹಾಕಿ",
  "generalInfo": "ಸಾಮಾನ್ಯ ಮಾಹಿತಿ",
  "materialCode": "ವಸ್ತು ಕೋಡ್",
  "materialDescription": "ವಸ್ತು ವಿವರಣೆ",
  "purchaseOrderNumber": "ಖರೀದಿ ಆದೇಶ ಸಂಖ್ಯೆ",
  "grnNumber": "GRN ಸಂಖ್ಯೆ",
  "supplierInfo": "ಪೂರೈಕೆದಾರರ ಮಾಹಿತಿ",
  "supplierName": "ಪೂರೈಕೆದಾರ ಹೆಸರು",
  "supplierId": "ಪೂರೈಕೆದಾರ ಐಡಿ",
  "invoiceNumber": "ಬಿಲ್ಲು ಸಂಖ್ಯೆ",
  "storageLocation": "ಸಂಗ್ರಹ ಸ್ಥಳ",
  "warehouseCode": "ಗೋದಾಮಿನ ಕೋಡ್",
  "storageBin": "ಸಂಗ್ರಹ ಬಿನ್",
  "deliveryInfo": "ವಿತರಣಾ ಮಾಹ��ತಿ",
  "deliveryNumber": "ವಿತರಣಾ ಸಂಖ್ಯೆ",
  "deliveryType": "ವಿತರಣಾ ಪ್ರಕಾರ",
  "vehicleNumber": "ವಾಹನ ಸಂಖ್ಯೆ",
  "inwardDetails": "ಊರ್ವೆ ವಿವರಗಳು",
  "receiptDateTime": "ಸ್ವೀಕೃತಿ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "gateDockNumber": "ಗೇಟ್ ಡಾಕ್ ಸಂಖ್ಯೆ",
  "attachmentDocument": "ಅಟಾಚ್‌ಮೆಂಟ್ ಡಾಕ್ಯುಮೆಂಟ್",
  "attachment": "ಅಟಾಚ್‌ಮೆಂಟ್",


  "boxNumber": "ಬಾಕ್ಸ್ ಸಂಖ್ಯೆ",
  "boxCapacity": "ಬಾಕ್ಸ್ ಸಾಮರ್ಥ್ಯ",
  "packetId": "ಪ್ಯಾಕೆಟ್ ಐಡಿ",
  "packetDescription": "ಪ್ಯಾಕೆಟ್ ವಿವರಣೆ",
  "remainingCapacity": "ಉಳಿದ ಸಾಮರ್ಥ್ಯ",
  "totalPacketsInBox": "ಬಾಕ್ಸ್‌ನಲ್ಲಿ ಒಟ್ಟು ಪ್ಯಾಕೆಟ್ಗಳು",

  // =====================================================================

  "reasonCodeAppTitle": "ಕಾರಣ ಕೋಡ್ ನಿರ್ವಹಣೆ",
  "reasonCode": "ಕಾರಣ ಕೋಡ್",
  "category": "ವರ್ಗ",
  "messageType": "ಸಂದೇಶ ಪ್ರಕಾರ",
  "createReasonCode": "ಕಾರಣ ಕೋಡ್ ರಚಿಸಿ",
  rowSelectionMsg: "ನೀವು ಸಾಲು ಆಯ್ಕೆಯನ್ನು ಮುಂದುವರಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
  "selectMessageType": "ಸಂದೇಶ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectResource": "ಸಂಪನ್ಮೂಲವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectWorkCenter": "ಕಾರ್ಯ ಕೇಂದ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectContainer": "ಕಂಟೈನರ್ ಆಯ್ಕೆಮಾಡಿ",

  "consumptionAndPackingAppTitle": "ಖರ್ಚು ಮತ್ತು ಪ್ಯಾಕಿಂಗ್",
  //=============================================================


  "routingTitle": "ರೌಟಿಂಗ್ ನಿರ್ವಹಣೆ",
  "routingType": "ರೌಟಿಂಗ್ ಪ್ರಕಾರ",
  "routingSteps": "ರೌಟಿಂಗ್ ಹಂತಗಳು",
  "subType": "ಉಪ ಪ್ರಕಾರ",
  "dispositionGroup": "ವಿತರಣಾ ಗುಂಪು",
  "relaxedRoutingFlow": "ರಿಲ್ಯಾಕ್ಸ್‌ಡ್ ಫ್ಲೋ ರೌಟಿಂಗ್",
  "replicationToErp": "ಇಆರ್‌ಪಿ ಗೆ ಪ್ರತಿದಾನ",
  "details": "ವಿವರಗಳು",
  "nextStepId": "ಮುಂದಿನ ಹಂತಗಳ ಐಡಿ",
  "stepId": "ಹಂತ ಐಡಿ",
  "stepType": "ಹಂತದ ಪ್ರಕಾರ",
  "stepDescription": "ಹಂತದ ವಿವರಣೆ",
  "previousStepId": "ಹಿಂದಿನ ಹಂತಗಳ ಐಡಿ",
  "maximumLoopCount": "ಗರಿಷ್ಠ ಲೂಪ್ ಎಣಿಕೆ",
  "queueDecision": "ಪ್ರಧಾನ ನಿರ್ಧಾರ",
  "erpControlKey": "ಇಆರ್‌ಪಿ ನಿಯಂತ್ರಣ ಕೀ",
  "erpOperation": "ಇಆ್‌ಪಿ ಕಾರ್ಯಾಚರಣೆ",
  "erpWorkCenter": "ಇಆರ್‌ಪಿ ಕಾರ್ಯ ಕೇಂದ್ರ",
  "requiredTimeInProcess": "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ ಬೇಕಾದ ಸಮಯ",
  "specialInstruction": "ವಿಶೇಷ ಸೂಚನೆ",
  "erpSequence": "ಇಆರ್‌ಪಿ ಕ್ರಮ",
  "blockPcusUntilInspectionFinished": "ನಿರೀಕ್ಷಣೆ ಮುಗಿಯುವವರೆಗೂ PCUs ಅನ್ನು ತಡೆ",
  "entryStep": "ಪ್ರವೇಶ ಹಂತ",
  "isLastReportingStep": "ಅಂತಿಮ ವರದಿ ಹಂತ",
  "reworkStep": "ಪುನಃಕಾರ್ಯ ಹಂತ",
  "routingStepDetails": "ರೌಟಿಂಗ್ ಹಂತದ ವಿವರಗಳು",
  "routingDescription": "ರೌಟರ್ ವಿವರಣೆ",
  "insertBefore": "ಮೊದಲಿನಿಂದ ಸೇರಿಸಿ",
  "insertAfter": "ನಂತರ ಸೇರಿಸಿ",
  "createRouting": "ಮಾರ್ಗಗಳನ್ನು ರಚಿಸಿ",
  "operation": "ಆಪರೇಶನ್",
  "trackOee": "ಒಇಇ ಹಿಂಬಾಲನೆ",
  "operationId": "ಆಪರೇಶನ್ ಐಡಿ",
  "operationVersion": "ಆಪರೇಶನ್ ಆವೃತ್ತಿ",
  "workListPanel": "ಕೆಲಸದ ಪಟ್ಟಿಯ ಪ್ಯಾನಲ್",

  // ============================= Activity =======================
  "activityAppTitle": "ಕಾರ್ಯಚಟುವಟಿಕೆ ನಿರ್ವಹಣೆ",
  "activity": "ಚಟುವಟಿಕೆ",
  "activityIds": "ಚಟುವಟಿಕೆ ಐಡಿ",
  "activityGroup": "ಚಟುವಟಿಕೆ ಗುಂಪು",
  "remove": "ಅಳಿಸಿ",
  "enabled": "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
  "visibleInActivityManager": "ಚಟುವಟಿಕೆ ನಿರ್ವಾಹಕದಲ್ಲಿ ಗೋಚರಿಸುತ್ತದೆ",
  "type": "ಪ್ರಕಾರ",
  "classOrProgram": "ತರಗತಿ / ಕಾರ್ಯಕ್ರಮ",
  "listOfMethod": "ವಿಧಾನಗಳ ಪಟ್ಟಿಯ",
  "createActivity": "ಚಟುವಟಿಕೆ ಸೃಷ್ಟಿಸಿ",
  "activityRules": "ಚಟುವಟಿಕೆ ನಿಯಮಗಳು",
  "activityHooks": "ಚಟುವಟಿಕೆ ಹೂಕ್ಸ್",
  "userArgument": "ಬಳಕೆದಾರ ವಾದ",
  "sites": "ಸೈಟ್",
  "hookableMethod": "ಹೂಕಬಲ್ ವಿಧಾನ",
  "hookPoint": "ಹೂಕ್ ಪಾಯಿಂಟ್",
  "rules": "ನಿಯಮಗಳು",
  "setting": "ಹೊಂದಾಣಿಕೆ",
  "addRules": "ನಿಯಮಗಳನ್ನು ಸೇರಿಸಿ",
  "addRule": "ನಿಯಮವನ್ನು ಸೇರಿಸಿ",
  restoreDefault: "ಡೀಫಾಲ್ಟ್ ಅನ್ನು ಪುನಃಸ್ಥಾಪಿಸಿ",
  "selectActivity": "ಚಟುವಟಿಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",

  // ========================== WORK CENTER =========================
  "workCenterAppTitle": "ಕಾರ್ಯ ಕೇಂದ್ರ ನಿರ್ವಹಣೆ",
  "workCenterCategory": "ಕಾರ್ಯ ಕೇಂದ್ರ ವರ್ಗ",
  "defaultParentWorkCenter": "ಡೀಫಾಲ್ಟ್ ಮೂಲ ಕಾರ್ಯ ಕೇಂದ್ರ",
  "defaultWorkCenter": "ಡೀಫಾಲ್ಟ್ ಕಾರ್ಯ ಕೇಂದ್ರ",
  "createWorkCenter": "ಕಾರ್ಯ ಕೇಂದ್ರ ರಚಿಸಿ",
  "association": "ಸಂಘ",
  "associateId": "ಅಸೋಸಿಯೇಟ್ ಐಡಿ",
  "defaultResource": "ಡೀಫಾಲ್ಟ್ ಸಂಪನ್ಮೂಲ",
  "deleteWCMessage": "ನೀವು ಈ ಕೆಲಸದ ಕೇಂದ್ರವನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದೆಯೇ",
  "disabled": "ಅಚಲಿತ",
  "closeMsg": "ನೀವು ಪುಟವನ್ನು ಬಿಟ್ಟುಹೋಗಲು ಖಚಿತವಾಗಿದೆಯೇ?",
  "yes": "ಹೌದು",
  "no": "ಇಲ್ಲ",
  "ok": "ಸರಿ",
  "select": "ಆಯ್ಕೆ",
  "confirmation": "ದೃಢೀಕರಣ",
  "selectAssociateId": "ಸಂಬಂಧಿತ ಐಡಿ ಆಯ್ಕೆಮಾಡಿ",
  "closePageMsg": "ನೀವು ನಿಜವಾಗಿಯೂ ನಿರ್ಗಮಿಸಲು ಬಯಸುಿರಾ?",
  "leavePage": "ಪೇಜ್ ಬಿಟ್ಟುಬಿಡಿ",
  "router": "ರೌಟರ್",
  "prelautid": "ಪೂರ್ವ ಲಾಟಿಡ್",
  "materialName": "ವಸ್ತು ಹೆಸರು",
  "uom": "ಮಾಪನ ಏಕಕ",
  "expectedQty": "ಕೋರಲಾಗುವ ಪ್ರಮಾಣ",
  "unit": "ಏಕಕ",
  "receivedQty": "ಸ್ವೀಕೃತ ಪ್ರಮಾಣ",
  "actions": "ಕೃತ್ಯಗಳು",

  "headerTitle": "ಶಿಫ್ಟ್ ನಿರ್ವಹಣೆ",
  "siteMaintenance": "ಸೈಟ್ ನಿರ್ವಹಣೆ",
  "batchNo": "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ",
  "pcu": "ಪಿಸಿಯು ",
  "itemBO": "ವಸ್ತು ",
  "routerBO": "ರೌಟರ್ ",
  "qty": "ಮಟ್ಟ",
  "shopOrderBO": "ಅಂಗಡಿಯ ಆದೇಶ ",
  "pod": "ಪಾಡ್",
  "timeZone": "ಟೈಮ್ ಝೋನ್",
  "local": "ಸ್ಥಳೀಯ",
  "site": "ಸೈಟ್ ನಿರ್ವಹಣೆ",
  "shift": "ಶಿಫ್ಟ್",
  "shopOrder": "ಅಂಗಡಿಕೆಗೆ ಆದೇಶ",
  "userHeaderTitle": "ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ",
  "serialNumber": "ಅಂಕಿತ ಸಂಖ್ಯೆ",
  "pcuNumber": "ಪಿಸಿಇಯು ಸಂಖ್ಯೆ",
  "underDeliveryTolerance": "ಡಿಸ್ಪ್ಯಾಚ್ ಸಹಿಷ್ಣುತೆ",
  "defineDeliveryToleranceIn": "ಮಟ್ಟದ ತಾಳ್ಮೆ ವ್ಯಾಖ್ಯಾನಿಸಿ",
  "doneQty": "ಮುಗಿಯುವ ಪ್ರಮಾಣ",
  "releasedQty": "ಬಿಟ್ಟ ಪ್ರಮಾಣ",
  "qtyInQueueOrWork": "ಕ್ಯೂ ಅಥವಾ ಕೆಲಸದಲ್ಲಿ ಪ್ರಮಾಣ",
  "scrappedQty": "ಕಳ್ಳತನ ಮಾಡಲಾದ ಪ್ರಮಾಣ",
  "unreleasedQty": "ಬಿಟ್ಟದೆಲ್ಲದ ಪ್ರಮಾಣ",
  "buildQty": "ನಿರ್ಮಾಣ ಪ್ರಮಾಣ",
  "recommendedBuildQtyToReachOrderedQty": "ಆರ್ಡರ್ ಮಾಡಿದ ಪ್ರಮಾಣವನ್ನು ತಲುಪಲು ಶಿಫಾರಸು ಮಾಡಲಾದ ಪ್ರಮಾಣ",
  "recommendedBuildQtyToReachMinimumDeliveryQty": "ಕೀಟಿಕ ಡೆಲಿವರಿ ಪ್ರಮಾಣವನ್ನು ತಲುಪಲು ಶಿಫಾರಸು ಮಾಡಲಾದ ಪ್ರಮಾಣ",
  "temperature": "ತಾಪಮಾನ",
  "overDeliveryTolerance": "ಮೆಟ್ರಿಕ್ ಪೂರೈಕೆ ಸಹಿಷ್ಣುತೆ",
  "maximumDeliveryQty": "ಹೆಚ್ಚುಮಟ್ಟದ ಡೆಲಿವರಿ ಪ್ರಮಾಣ",
  "minimumDeliveryQty": "ಕೀಟಿಕ ಡೆಲಿವರಿ ಪ್ರಮಾಣ",
  "unlimited_over_delivery": "ಅನ್ಲಿಮಿಟೆಡ್ ಓವರ ಡೆಲಿವರಿ",
  "pcuQuantity": "ಪಿಸಿಇಯು ಪ್ರಮಾಣ",
  "state": "ರಾಜ್ಯ",
  "user": "ಬಳಕೆದಾರ",
  "noOfCount": "ಶಿಫ್ಟ್",
  "shiftType": "ಶಿಫ್ಟ್ ಪ್ರಕಾರ",
  "material": "ಪದಾರ್ಥ",
  "cycleTime": "ಚಕ್ರ ಕಾಲ",
  "manufacturedTime": "ತಯಾರಿತ ಸಮಯ",
  "createCycleTime": "ಚಕ್ರ ಸಮಯವನ್ನು ರಚಿಸು",
  "materialVersion": "ಪದಾರ್ಥ ಆವೃತ್ತಿ",
  "update": "ನವೀಕರಿಸಿ",
  "shiftInterval": "ಶಿಫ್ಟ್ ಅಂತರ",
  "calendarRules": "ಕ್ಯಾಲೆಂಡರ್ ನಿಯಮಗಳು",
  "createdOn": "ರಚಿಸಲಾಗಿದೆ",
  "modifiedOn": "ತಿದ್ದುಪಡಿ ಮಾಡಲಾಗಿದೆ",
  "erpShift": "ಇಆರ್‌ಪಿ ಶಿಫ್ಟ್",
  "confirm": "ದೃಢೀಕರಿಸು",
  "alertRow": "ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಸಾಲಿನೊಂದಿಗೆ ಮುಂದುವರಿಯಲು ಬಯಸುತ್ತೀರಾ?",
  "addBreak": "ಬ್ರೇಕ್ ಸೇರಿಸಿ",
  "Status": "ಸ್ಥಿತಿ",
  "comment": "ಕಾಮೆಂಟ್",
  "newStatus": "ಹೊಸ ಸ್ಥಿತಿ",
  "selectBy": "ಆಧಾರಿತ ಆಯ್ಕೆ ಮಾಡಿ",
  "validityShiftInfo": "ವಾಲಿಡಿಟಿ/ಶಿಫ್ಟ್ ಮಾಹಿತಿಯು",
  "clockInOutInfo": "ಕ್ಲಾಕ್-ಇನ್/ಔಟ್ ಮಾಹಿತಿಯು",
  "labourInfo": "ಶ್ರಮ ಮಾಹಿತಿಯು",
  "action": "ಕ್ರಿಯೆ",
  "day": "ದಿನ",
  "productionDay": "ಉತ್ಪಾದನೆ ದಿನ",
  "dayClass": "ದಿನ ವರ್ಗ",
  "search": "ಹುಡುಕಿ",
  "maintenance": "ನಿರ್ವಹಣೆ",
  "certification": "ಪ್ರಮಾಣಪತ್ರ",
  "subStep": "ಉಪ-ಹಂತ",
  "activityHook": "ಚಟುವಟಿಕೆ ಹುಕ್",
  "operationType": "ಆಪರೇಶನ್ ಪ್ರಕಾರ",
  "resourceType": "ಸಾಧನ ಪ್ರಕಾರ",
  "defaultOperation": "ಮೂಲ ಆಪರೇಶನ್",
  "addAsErpOperation": "ಇಆರ್‌ಪಿ ಆಪರೇಶನ್ ಆಗಿ ಸೇರಿಸಿ",
  "maxLoopCount": "ಹೆಚ್ಚಿನ ಲೂಪ್ ಸಂಖ್ಯಾ",
  "enter": "ನೀಡಿ",
  "employeeNumber": "ಮೂಕಿಂಗ್ ಸಂಖ್ಯೆ",
  "hireDate": "ಆಹ್ವಾನ ದಿನಾಂಕ",
  "erpUser": "ಇಆರ್‌ಪಿ ಬಳಕೆದಾರ",
  "firstName": "ಮೊದಲ ಹೆಸರ",
  "lastName": "ಅಂತಿಮ ಹೆಸರು",
  "emailAddress": "ಇಮೇಲ್ ವಿಳಾಸ",
  "erpPersonnelNumber": "ಇಆರ್‌ಪಿ ವೈಯಕ್ತಿಕ ಸಂಖ್ಯೆ",
  "sl_no": "ಕ್ರಮ ಸಂಖ್ಯೆ",
  "packet_id": "ಪ್ಯಾಕೆಟ್ ಐಡಿ",
  "packet_description": "ಪ್ಯಾಕೆಟ್ ವಿವರಣೆ",
  "qty_consumed": "ಬಳಸಿದ ಪ್ರಮಾಣ",
  "total_packets": "ಒಟ್ಟು ಪ್ಯಾಕೆಟ್‌ಗಳು",
  "remaining_capacity": "ಉಳಿತಾಯ ಸಾಮರ್ಥ್ಯ",
  "userGroup": "ಬಳಕೆದಾರ ಗುಂಪು",
  "labourTracking": "ಶ್ರಮ ಹಿಂಬಾಲಿಸುವಿಕೆ",
  "supervisor": "ಮೂಲಕ",
  "labourRule": "ಶ್ರಮ ನಿಯಮ",
  "bomType": "ಬೋಮ್ ಪ್ರಕಾರ",
  "plannedBom": "ಯೋಚಿಸಲಾದ ಬೋಮ್",
  "plannedRouting": "ಯೋಚಿಸಲಾದ ಮಾರ್ಗಸೂಚಿ",
  "lcc": "ಎಲ್‌ಸಿಸಿ",
  "plannedWorkCenter": "ಯೋಚಿಸಲಾದ ಕೆಲಸದ ಕೇಂದ್ರ",
  "orderedQty": "ಆದೇಶಿತ ಪ್ರಮಾಣ",
  "priority": "ಪ್ರಾಮುಖ್ಯತೆ",
  "erpUom": "ಇಆರ್‌ಪಿ ಯುಒಎಮ್",
  "plannedStart": "ಯೋಚಿಸಲಾದ ಆರಂಭ",
  "plannedCompletion": "ಯೋಚಿಸಲಾದ ಪೂರ್ಣಗೊಳ್ಳುವುದು",
  "scheduledStart": "ನಿಯೋಜಿತ ಆರಂಭ",
  "scheduledEnd": "ನಿಯೋಜಿತ ಅಂತ್ಯ",
  "customerOrder": "ಗ್ರಾಹಕ ಆದೇಶ",
  "customer": "ಗ್ರಾಹಕ",
  "orderType": "ಆದೇಶ ಪ್ರಕಾರ",
  "plannedMaterial": "ಯೋಚಿಸಲಾದ ಪದಾರ್ಥ",
  "productionQuantities": "ಉತ್ಪಾದನಾ ಪ್ರಮಾಣಗಳು",
  "serialPCU": "ಸೀರಿಯಲ್ ಪಿಸಿಯು",
  "enable": "ಆಗೋಷ್ಟ",
  "bomMaintenance": "ಬೋಮ್ ನಿರ್ವಹಣೆ",
  "bomTemplate": "ಬೋಮ್ ಟೆಂಪ್ಲೇಟ್",
  "component": "ಘಟಕ",
  "assemblyOperation": "ಅಸೆಂಬ್ಲಿ ಆಪರೇಶನ್",
  "assemblyQuantity": "ಅಸೆಂಬ್ಲಿ ಪ್ರಮಾಣ",
  "copyBom": "ನಕಲು ಬೋಮ್",
  "updateBom": "ನವೀಕರಿಸಿ ಬೋಮ್",
  "assemblySequence": "ಅಸೆಂಬ್ಲಿ ಕ್ರಮ",
  "componentType": "ಘಟಕ ಪ್ರಕಾರ",
  "maxNc": "ಅತ್ಯದಿಕ ಎನ್‌ಸಿ",
  "maxUsage": "ಅತ್ಯದಿಕ ಬಳಸುವಿಕೆ",
  "createBomComponent": "ಬೋಮ್ ಘಟಕವನ್ನು ರಚಿಸಿ",
  "createNewBom": "ಹೊಸ ಬೊಮ್ ಅನ್ನು ರಚಿಸಿ",
  "alternateComponentVersion": "ಆಪ್ತಘಟಕ ಆವೃತ್ತಿ",
  "designCost": "ಡಿಸೈನ್ ವೆಚ್ಚ",
  "assySequence": "ಅಸಂಬ್ಲಿ ಕ್ರಮ",
  "componentVersion": "ಸಾಧನ ಆವೃತ್ತಿ",
  "componentDescription": "ಸಾಧನ ವರ್ಣನೆ",
  "assyQty": "ಅಸಂಬ್ಲಿ ಪ್ರಮಾಣ",
  "assyOperation": "ಅಸಂಬ್ಲಿ ಕಾರ್",
  "assemblyDataTypeBo": "ಅಸಂಬ್ಲಿ ಡೇಟಾ ಶ್ರೇಣಿ ",
  "storageLocationBo": "ಸಂಗ್ರಹಣಾ ಸ್ಥಳ ",
  "close": "ಮುಚ್ಚು",
  "availableActivities": "ಉಪಲಬ್ಧ ಚಟುವಟಿಕೆಗಳು",
  "assignedActivities": "ನಿಯೋಜಿತ ಚಟುವಟಿಕೆಗಳು",
  "activities": "ಚಟುವಟಿಕೆಗಳು",
  "activityGroupName": "ಚಟುವಟಿಕೆ ಗುಂಪು ಹೆಸರು",
  "activityGroupMaintenance": "ಚಟುವಟಿಕೆ ಗುಂಪು ನಿರ್ವಹಣೆ",
  "createActivityGroup": "ಚಟುವಟಿಕೆ ಗುಂಪು ರಚಿಸಿ",
  "activityGroupDescription": "ಚಟುವಟಿಕೆ ಗುಂಪು ವಿವರಣೆ",
  "copyActivityGroup": "ನಕಲು ಚಟುವಟಿಕೆ ಗುಂಪು",
  "selectRouting": "ಮಾರ್ಗದರ್ಶನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "container": "ಕಂಟೈನರ್",
  "hold": "ಹೋಲ್ಡ್",
  "receive": "ಸ್ವೀಕರಿಸು",
  "reject": "ತಿರಸ್ಕರಿಸು",


  // ===============================   Next Number     ==============================
  "numbeType": "ಸಂಖ್ಯಾ ಪ್ರಕಾರ",
  "definedBy": "ನಿರ್ದಿಷ್ಟಗೊಳಿಸಲಾಗಿದೆ",
  "objectVersion": "ವಸ್ತುವಿನ ಆವೃತ್ತಿ",
  "containerInput": "ಕಂಟೈನರ್ ಇನ್ಪುಟ್",
  "prefix": "ಆರಂಭಿಕ",
  "suffix": "ಉಪಸರ್ಗ",
  "numberBase": "ಸಂಖ್ಯಾ ಮೂಲ",
  "sequenceLength": "ಆಗತದ ಉದ್ದ",
  "minSequence": "ಕನಿಷ್ಠ ಕ್ರಮ",
  "maxSequence": "ಅತಿದೊಡ್ಡ ಕ್ರಮ",
  "warningThreshold": "ಎಚ್ಚರಿಕೆ ಹಾರಿ",
  "incrementBy": "ಹೆಚ್ಚಿಸುವುದು",
  "currentSequence": "ಪ್ರಸ್ತುತ ಕ್ರಮ",
  "resetSequenceNumber": "ಕ್ರಮ ಸಂಖ್ಯೆಯನ್ನು ಪುನರಾವೃತ್ತ ಮಾಡು",
  "nextNumberActivity": "ಮುಂದಿನ ಸಂಖ್ಯಾ ಕ್ರಿಯೆ",
  "createContinuousSfc": "ಆಮದಿಯಲ್ಲಿ ನಿರಂತರ ಎಸ್‌ಎಫ್‌ಸಿಯನ್ನು ರಚಿಸು",
  "commitNextNumberChangesImmediately": "ಮುಂದಿನ ಸಂಖ್ಯಾ ಬದಲಾವಣೆಗಳನ್ನು ತಕ್ಷಣವೇ ಬದಲಾಗಿಸು",
  "sampleNextNumber": "ಉದಾಹರಣೆಯ ಮುಂದಿನ ಸಂಖ್ಯಾ",
  "nextNumberAppTitle": "ಮುಂದಿನ ಸಂಖ್ಯೆ ನಿರ್ವಹಣೆ",
  "parametersAndDescription": "ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು ಮತ್ತು ವಿವರ",
  "selectItemGroup": "ಐಟಂ ಗುಂಪು ಆಯ್ಕೆಮಾಡಿ",
  "selectDataType": "ಡೇಟಾ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "selectBOM": "ಬಿಒಎಮ್ ಆಯ್ಕೆಮಾಡಿ",
  "selectItem": "ಐಟಂ ಆಯ್ಕೆಮಾಡಿ",
  "retrieve": "ಮತ್ತೆ ಪಡೆಯಿರಿ",
  "clear": "ಸ್ಪಷ್ಟ",
  "createNextNumber": "ಮುಂದಿನ ಸಂಖ್ಯೆಯನ್ನು ರಚಿಸಿ",



  "podMaintenance": "ಪೋಡ್ ನಿರ್ವಹಣೆ",
  "podName": "ಪೋಡ್ ಹೆಸರು",
  "createPodName": "ಪೋಡ್ ಹೆಸರು ರಚಿಸಿ",
  "podLayout": "ಪೋಡ್ ವಿನ್ಯಾಸ",
  "kafkaIntegration": "ಕಾಫ್ಕಾ ಇಂಟಿಗ್ರೇಶನ್",
  "kafkaId": "ಕಾಫ್ಕಾ ಐಡಿ",
  "operationCanBeChanged": "ಕ್ರಿಯೆ ಬದಲಾಯಿಸಲಾಗುತ್ತದೆ",
  "resourceCanBeChanged": "ಆಸ್ಪತ್ರೆ ಬದಲಾಯಿಸಬಹುದು",
  "showQuantity": "ಮಟ್ಟವನ್ನು ತೋರಿಸಿ",
  "documentName": "ಡಾಕ್ಯುಮೆಂಟ ಹೆಸರು",
  "sessionTimeout": "ಸೆಷನ್ ಟೈಮ್ಔಟ್",
  "refreshRate": "ರಿಫ್ರೆಶ್ ಶ್ರೇಣಿಯು",
  "podType": "ಪೋಡ್ ಪ್ರಕಾರ",
  "copyPod": "ಪೋಡ್ ನಕಲು ಮಾಡಿ",
  "updatePod": "ಪೋಡ್ ನವೀಕರಿಸಿ",
  "recipientName": "ಸ್ವೀಕರಿಸುವವರ ಹೆಸರು",
  "recipientId": "ಸ್ವೀಕರಿಸುವವರ ಐಡಿ",
  "buttonId": "ಬಟನ್ ಐಡಿ",
  "buttonLabel": "ಬಟನ್ ಲೇಬಲ್",
  "buttonType": "ಬಟನ್ ಪ್ರಕಾರ",
  "buttons": "ಬಟನ್ಗಳು",
  "listOptions": "ಓಹುಪರಿವಾರ",
  "podSelections": "ಪೋಡ್ ಆಯ್ಕೆಗಳು",
  "printers": "ಮುದ್ರಕಗಳು",
  "home": "ಮನೆ",
  "buttonSize": "ಬಟನ್ ಗಾತ್ರ",
  "imageIcon": "ಇಮೇಜ್ ಐಕಾನ್",
  "hotKey": "ಹಾಟ್ ಕೀ",
  "buttonLocation": "ಬಟನ್ ಸ್ಥಳ",
  "podSelection": "ಪೋಡ್ ಆಯ್ಕೆ",
  "activitySequence": "ಚಟುವಟಿಕೆ ಕ್ರಮ",
  "pluginLocation": "ಪ್ಲಗಿನ್ ಸ್ಥಳ",
  "clearsPcu": "ಪಿಸಿಯು ಅಳಿಸಿ",
  "fixed": "ನಿರ್ಧರಿತ",
  "createNewPod": "ಹೊಸ ಪೊಡ್ ರಚಿಸಿ",
  "panelLayout": "ಪ್ಯಾನಲ್ ವಿನ್ಯಾಸ",
  "selectDefaultOperation": "ಮೂಲ ಕ್ರಿಯೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectDefaultResource": "ಮೂಲ ಸಂಪತ್ತನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectDocumentName": "ಡಾಕ್ಯುಮೆಂಟ್ ಹೆಸರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "browseWorkList": "ಕೆಲಸದ ಪಟ್ಟಿಯನ್ನು ವೀಕ್ಷಿಸಿ",
  "podWorkList": "ಪೋಡ್ ಕೆಲಸದ ಪಟ್ಟಿಯು",
  "assembleList": "ಆಸಂಬ್ಲಿ ಪಟ್ಟಿಯು",
  "dcCollectList": "ಡಿಸಿ ಸಂ��್ರಹ ಪಟ್ಟಿಯು",
  "toolList": "ಉಪಕರಣ ಪಟ್ಟಿಯು",
  "workInstructionList": "ಕೆಲಸದ ಸೂಚನೆಯ ಪಟ್ಟಿಯು",
  "dcEntryList": "ಡಿಸಿ ಎಂಟ್ರಿ ಪಟ್ಟಿಯು",
  "subStepList": "ಉಪ ಹಂತಗಳ ಪಟ್ಟಿ���ು",
  "mainInput": "ಮೂಲ ಇನ್ಪುಟ್",
  "mainInputHotKey": "ಮೂಲ ಇನ್ಪುಟ್ ಹಾಟ್ ಕೀ",
  "infoLine1": "ಮಾಹಿತಿ ಸಾಲು 1",
  "infoLine2": "ಮಾಹಿತಿ ಸಾಲು 2",
  "documentPrinter": "ಡಾಕ್ಯುಮೆಂಟ್ ಪ್ರಿಂಟರ್",
  "labelPrinter": "ಲೇಬಲ್ ಪ್ರಿಂಟರ್",
  "travelerPrinter": "ಮ್ಯಾಪರ್ ಪ್ರಿಂಟರ್",
  "materialInwardManagement": "ವಸ್ತು ಒಳಹೋಗುವ ನಿರ್ವಹಣೆ",

  "users": "ಬಳಕೆದಾರರು",
  "userGroupMaintenance": "ಬಳಕೆದಾರ ಗುಂಪು ನಿರ್ವಹಣೆ",
  "selectPod": "ಪಾಡ್ ಆಯ್ಕೆ ಮಾಡಿ",
  "availableUsers": "ಉಪಲಭ್ಯ ಬಳಕೆದಾರರು",
  "assignedUsers": "ನಿಯೋಜಿತ ಬಳಕೆದಾರರು",
  "availableActivityGroups": "ಉಪಲಭ್ಯ ಚಟುವಟಿಕೆ ಗುಂಪುಗಳು",
  "assignedActivityGroups": "ನಿಯೋಜಿತ ಚಟುವಟಿಕೆ ಗುಂಪುಗಳು",


  "pickListManagement": "ಪಿಕ್ ಲಿಸ್ಟ್ ನಿರ್ವಹಣೆ",
  "pickListNo": "ಪಿಕ್ ಲಿಸ್ಟ್ ನಂ",
  "orderNo": "ಆರ್ಡರ್ ನಂ",
  "generate": "ಸೃಷ್ಟಿ",
  "itemCode": "ಐಟಂ ಕೋಡ್",
  "itemDescription": "ಐಟಂ ವಿವರಣೆ",
  "qtyOrdered": "ಆರ್ಡರ್ ಮಾಡಿರುವ ಪ್ರಮಾಣ",
  "qtyPicked": "ಹೊರಹಾಕಿದ ಪ್ರಮಾಣ",
  "location": "ಸ್ಥಳ",
  "warehouse": "ಗೋದಾಮು",
  "pick": "ತಗೆ",
  "updatePick": "ತಗೆಯುವುದು ನವೀಕರಿಸಿ",
  "print": "ಮುದ್ರಣ",
  "selectOrder": "ಆರ್ಡರ್ ಆಯ್ಕೆ ಮಾಡಿ",
  "resourceMaintenance": "ಸಾಧನ ನಿರ್ವಹಣೆ",
  "createResource": "ಸಾಧನವನ್ನು ರಚಿಸು",
  "opcTag": "ಓಪಿಸಿ ಟ್ಯಾಗ್",
  "processResource": "ಸಾಧನವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸು",
  "erpEquipmentNumber": "ಈರಪಿ ಸಾಧನ ಸಂಖ್ಯೆ",
  "erpPlantNumber": "ಈರಪಿ ಗಿಡ ಸಂಖ್ಯೆ",
  "availableResource": "ಲಭ್ಯವಿರುವ ಸಂಪತ್ತು",
  "assignedResource": "ನಿಯೋಜಿತ ಸಂಪತ್ತು",
  "tagName": "ಟ್ಯಾಗ್ ಹೆಸರು",
  "tagUrl": "ಟ್ಯಾಗ್ URL",
  "identity": "ಪರಿಚಯ",
  "selectCertification": "ಪ್ರಮಾಣಪತ್ರ ಆಯ್ಕೆ ಮಾಡಿ",
  "cycleTimeMaintenance": "ಚಕ್ರ ಕಾಲ ನಿರ್ವಹಣೆ",
  "dataType": "ಡೇಟಾ ಪ್ರಕಾರ",
  "manageAlternateComponents": "ಬದಲಿಯಾದ ಘಟಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  "manageParentComponents": "ಮೂಲ ಘಟಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  "selectComponent": "ಪೊರೆಯ ಆಯ್ಕೆ ಮಾಡಿ",
  "selectAssemblyOperation": "ಸಂಗ್ರಹಣ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "selectAssemblyDataType": "ಸಂಗ್ರಹಣ ಡೇಟಾ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "selectAlternateComponent": "ಬದಲಿ ಘಟಕವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "selectOperation": "ಕ್ರಿಯೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectMaterial": "ವಸ್ತುವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "name": "ಹೆಸರು",
  "operationalSettingAppTitle": "ಆಪರೇಶನಲ್ ಸೆಟಿಂಗ್",
  "reset": "ಮೀಡು",
  "uomCode": "ಯುಒಎಂ ಕೋಡ್",
  "selectList": "ಪಟ್ಟಿ ಆಯ್ಕೆ ಮಾಡಿ",
  "list": "ಪಟ್ಟಿ",
  "selectPrinters": "ಮುದ್ರಕಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "deleteMsg": "ನೀವು ಈ ಮುಂದಿನ ಸಂಖ್ಯೆಯನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?",
  "parameter": "ಪ್ಯಾರಾಮೀಟರ್",
  "enterFullScreen": "ಪೂರ್ಣ ಪರದೆಯೊಳಗೆ ನುಸುಳಿ",
  "exitFullScreen": "ಪೂರ್ಣ ಪರೆಯಿಂದ ಹೊರಬರಿ",
  "release": "ಬಿಡುಗಡೆ",
  "shopOrderRelease": "ದೂಸು ಆದೇಶ ಬಿಡುಗಡೆ",
  "qtyToRelease": "ಬಿಡುಗಡೆಗೆ ಪ್ರಮಾಣ",
  "addToNewProcessLot": "ಹೊಸ ಪ್ರಕ್ರಿಯೆ ಸಮೂಹದಲ್ಲಿ ಸೇರಿಸಿ",
  "availableQtyToRelease": "ಬಿಡುಗಡೆಗೆ ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣ",
  "flowChart": "ಪ್ರವಾಹ ಚಾರ್ಟ್",
  "serialBatchNumber": "ಸೀರಿಯಲ್ ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ",
  "bnoQuantity": "ಬಿಎನ್‌ಒ ಪ್ರಮಾಣ",
  "bno": "ಬಿಎನ್‌ಒ",
  "detail": "ವಿವರ",
  "dcGroup": "ಡಿಸಿ ಗುಂಪು",
  "viewPdf": "ಪಿಡಿಎಫ್ ವೀಕ್ಷಿಸಿ",


  // ============================== ITEM GROUP ========================
  "itemGroupAppTitle": "ಐಟಂ ಗುಂಪು ನಿರ್ವಹಣೆ",
  "groupDescription": "ಗುಂಪು ವಿವರಣೆ",
  "unitPrice": "ಘಟಕ ಬೆಲೆ",
  "groupMember": "ಗುಂಪು ಸದಸ್ಯ",
  "createItemGroup": "ಐಟಂ ಗುಂಪು ರಚಿಸಿ",
  "itemGroupDeleteMessage": "ನೀವು ಈ ಐಟಂ ಗುಂಪನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ",

  "erpPlantMaintenanceOrder": "ಇಆರ್‌ಪಿ ಸಂಗ್ರಹಣಾ ಆದೇಶ",
  "availableResourceTypes": "ಕನಿಷ್ಠ ಸಂಪತ್ತುಗಳ ಪ್ರಕಾರ",
  "assignedResourceTypes": "ನಿಯೋಜಿತ ಸಂಪತ್ತುಗಳ ಪ್ರಕಾರ",
  "copyResource": "ನಕಲಿ ಸಂಪತ್ತು",
  "selectMethod": "ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "method": "ವಿಧಾನ",



  "resourceTypeMaintenance": "ಸಂಪತ್ತು ಪ್ರಕಾರ ನಿರ್ವಹಣೆ",
  "resourceTypeDescription": "ಸಂಪತ್ತು ಪ್ರಕಾರ ವಿವರಣೆ",
  "resourceMemberList": "ಸಂಪತ್ತು ಸದಸ್ಯರ ಪಟ್ಟಿ",
  "createResourceType": "ಸಂಪತ್ತು ಪ್ರಕಾರ ಸೃಷ್ಟಿಸಿ",
  "createUserGroup": "ಬಳಕೆದಾರ ಗುಂಪನ್ನು ರಚಿಸಿ",

  "customdataMaintenance": "ಕಸ್ಟಮ್ ಡೇಟಾ ನಿರ್ವಹಣೆ",
  "data field": "ಡೇಟಾ ಪ್ರಕಾರ",
  "field label": "ಪ್ರಕಾರ ಲೇಬಲ್",
  "required": "ಅಗತ್ಯವಿರುವ",
  "selectdataField": "ಡೇಟಾ ಪ್ರಕಾರ ಆಯ್ಕೆ ಮಾಡಿ",

  // ============================================== DATA FIELD ===========================================
  "dataField": "ಡೇಟಾ ಕ್ಷೇತ್ರ",
  "fieldLabel": "ಕ್ಷೇತ್ರ ಲೇಬಲ್",
  "dataFieldAppTitle": "ಡೇಟಾ ಕ್ಷೇತ್ರ ನಿರ್ವಹಣೆ",
  "maskGroup": "ಮಾಸ್ಕ್ ಗುಂಪು",
  "preSaveActivity": "ಉಳಿಸುವ ಮೊದಲಿನ ಚಟುವಟಿಕೆ",
  "isTrackable": "ಟ್ರ್ಯಾಕ್ ಮಾಡಬಹುದಾದುದು",
  "qmSelectedSet": "QM ಆಯ್ಕೆ ಮಾಡಿದ ಸೆಟ್",
  "isMrfRef": "MRF ಉಲ್ಲೇಖವೇ",
  "browseIcon": "ಬ್ರೌಸ್ ಐಕಾನ್",
  "defaultLabel": "ಡೀಫಾಲ್ಟ್ ಲೇಬಲ್",
  "fieldValue": "ಕ್ಷೇತ್ರ ಮೌಲ್ಯ",
  "labelValue": "ಲೇಬಲ್ ಮೌಲ್ಯ",
  "api": "ಎಪಿಐ",
  "width": "ಅಗಲ",
  "parameters": "ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು",
  "title": "ಶೀರ್ಷಿಕೆ",
  "editValues": "ಮೌಲ್ಯಗಳನ್ನು ಸಂಪಾದಿಸಿ",
  "createDataField": "ಡೇಟಾ ಫೀಲ್ಡ್ ರಚಿಸಿ",

  // ============================================== DATA TYPE ===========================================

  "dataTypeAppTitle": "ಡೇಟಾ ಪ್ರಕಾರ ನಿರ್ವಹಣೆ",
  "createDataType": "ಡೇಟಾ ಪ್ರಕಾರವನ್ನು ರಚಿಸಿ",
  "selectDataField": "ಡೇಟಾ ಕ್ಷೇತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "listDetails": "ಪಟ್ಟಿ ವಿವರಗಳು",

  "order": "ಆದೇಶ",
  "componentToScan": "ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಘಟಕ",
  "assembled": "ಸಂಪೂರ್ಣಗೊಂಡವು",
  "assemble": "ಸೆಟ್ಗಳನ್ನು ಸೇರಿಸಿ",
  "remaining": "ಉಳಿದಿರುವುದು",
  "dataAttribute": "ಡೇಟಾ ಗುಣಲಕ್ಷಣ",
  "returnToPod": "POD ಗೆ ಹಿಂದಿರುಗಿಸಿ",
  "confirmCreateDataField": "ಡೇಟಾ ಕ್ಷೇತ್ರ ಕಂಡುಬಂದಿಲ್ಲ, ನೀವು ಈ ಡೇಟಾ ಕ್ಷೇತ್ರವನ್ನು ರಚಿಸಲು ಬಯಸುತ್ತೀರಾ",
  "attachmentList": "ಅಟಾಚ್ಮೆಂಟ್ ಪಟ್ಟಿ",

  // ============================================= DC PLUGIN ===========================================
  "parameterList": "ಪ್ಯಾರಾಮೀಟರ್ ಪಟ್ಟಿ",
  "showDetails": "ವಿವರಗಳನ್ನು ತೋರಿಸಿ",
  "collectData": "ಡೇಟಾ ಸಂಗ್ರಹಿಸಿ",
  "saveDraft": "ಮಸೂದೆಯನ್ನು ಉಳಿಸಿ",
  "submit": "ಸಲ್ಲಿಸು",
  "dataFieldList": "ಡೇಟಾ ಕ್ಷೇತ್ರ ಪಟ್ಟಿ",
  "collectedDCParameterList": "ಸಂಗ್ರಹಿತ ಡಿಸಿ ಪ್ಯಾರಾಮೀಟರ್ ಪಟ್ಟಿ",
  "returnToDCList": "ಡಿಸಿ ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ",
  "range": "ಶ್ರೇಣಿಯ",
  "dateTime": "ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "collectionMethod": "ಸಂಗ್ರಹ ವಿಧಾನ",
  "parameterName": "ಪ್ಯಾರಾಮೀಟರ್ ಹೆಸರು",
  "collectDataAt": "ಡೇಟಾ ಸಂಗ್ರಹಿಸಲು",

  // =============================================== WORK INSTRUCTION ======================================
  "textInstruction": "ಪಠ್ಯ ಸೂಚನೆ", // Kannada
  "urlInstruction": "ಯುಆರ್‌ಎಲ್ ಸೂಚನೆ",
  "instructionType": "ನಿರ್ದೇಶನ ಪ್ರಕಾರ",
  "WorkInstruction_Description": "ವಿವರಣೆ",
  "WorkInstructionID_Revision": "ಕೆಲಸದ ನಿರ್ದೇಶನ / ಪರಿಷ್ಕರಣೆ",
  "Operation_StepId": "ಚಾಲನೆ ಹಂತ ಐಡಿ",
  "StepId": "ಹಂತ ಐಡಿ",


  "workInstructionMaintenance": "ಕೆಲಸದ ಸೂಚನೆ ನಿರ್ವಹಣೆ",
  "workInstruction": "ಕೆಲಸದ ಸೂಚನೆ",
  "createWorkInstruction": "ಕೆಲಸದ ಸೂಚನೆ ರಚಿಸಿ",
  "alwaysShowInNewWindow": "ಯಾವಾಗಲೂ ಹೊಸ ಕಿಟಕಿಯಲ್ಲಿ ತೋರಿಸಿ",
  "logViewing": "ಲಾಗ್ ವೀಕ್ಷಣೆ",
  "changeAlert": "ಬದಲಾವಣೆ ಎಚ್ಚರಿಕೆ",
  "erpWi": "ERP ಕೆಲಸದ ಸೂಚನೆ",
  "text": "ಪಠ್ಯ",
  "url": "ಯುಆರ್‌ಎಲ್",
  "file": "ಕಡತ",

  // ================================== SCRAP AND USER =======================

  "pcu/shopOrder/processLot": "ಪಿಸಿಯು / ಶಾಪ್ ಆರ್ಡರ್ / ಪ್ರೊಸೆಸ್ ಲಾಟ್",
  "comments": "ಟಿಪ್ಪಣಿಗಳು",
  "scrap": "ತ್ಯಾಜ್ಯ",
  "unscrap": "ತ್ಯಾಜ್ಯ ರದ್ದು",
  "Scrap": "ತ್ಯಾಜ್ಯ",
  "Unscrap": "ತ್ಯಾಜ್ಯ ರದ್ದು",
  "scrapUnscrapTitle": "ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ",
  "confirmPassword": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
  "password": "ಪಾಸ್‌ವರ್ಡ್",
  "selectSites": "ಸೈಟ್‌ಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "PCU": "ಪಿಸಿಯು",
  "Shop Order": "ಶಾಪ್ ಆರ್ಡರ್",
  "Process Lot": "ಪ್ರೊಸೆಸ್ ಲಾಟ್",
  "workflowIntegrationMaintenance": "ಕಾರ್ಯಪ್ರವಾಹ ಒಕ್ಕೂಟ ನಿರ್ವಹಣೆ",
  "workflowIntegration": "ಕಾರ್ಯಪ್ರವಾಹ ಒಕ್ಕೂಟ",
  "createWorkflowIntegration": "ಕಾರ್ಯಪ್ರವಾಹ ಒಕ್ಕೂಟವನ್ನು ರಚಿಸಿ",
  "identifier": "ಗುರುತಿಕೆ",
  "messageId": "ಸಂದೇಶ ಐಡಿ",
  "processBy": "ಇದರ ಮೂಲಕ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ",
  "transformationType": "ರಿವರ್ತನೆ ಪ್ರಕಾರ",
  "preprocessJolt": "ಪೂರ್ವ ಪ್ರಕ್ರಿಯೆ ಜೋಲ್ಟ್",
  "preprocessApi": "ಪೂರ್ವ ಪ್ರಕ್ರಿಯೆ API",
  "serviceApi": "ಸೇವಾ API",
  "expectedSplits": "ನಿರೀಕ್ಷಿತ ವಿಭಜನೆಗಳು",
  "postProcessJolt": "ಪ್ರಕ್ರಿಯೆ ನಂತರದ ಜೋಲ್ಟ್",
  "postProcessApi": "ಪ್ರಕ್ರಿಯೆ ನಂತರದ API",
  "passHandler": "ಹಸ್ತಾಂತರ ಮಾಡುವವನು",
  "failHandler": "ಅನುತ್ತೀರ್ಣ ಮಾಡುವವನು",
  "processTransformation": "ಪ್ರಕ್ರಿಯೆ ಪರಿವರ್ತನೆ",

  // ============================================== Jolt Spec ===========================================
  "specName": "ಸ್ಪೆಕ್ ಹೆಸರು",
  "specNamePlaceholder": "ಸ್ಪೆಕ್ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "specNameRequired": "ದಯವಿಟ್ಟು ಸ್ಪೆಕ್ ಹೆಸರನ್ನು ನಮೂದಿಸಿ!",

  "typePlaceholder": "ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "typeRequired": "ದಯವಿಟ್ಟು ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ!",
  "joltSpec": "ಜೋಲ್ಟ್ ಸ್ಪೆಕ್",
  "joltSpecPlaceholder": "ಜೋಲ್ಟ್ ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "xsltSpec": "XSLT ಸ್ಪೆಕ್",
  "xsltSpecPlaceholder": "XSLT ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "encodeXsltSpec": "ಎನ್ಕೋಡ್ XSLT ಸ್ಪೆಕ್",
  "encodeXsltSpecPlaceholder": "ಎನ್ಕೋಡ್ ಮಾಡಿದ XSLT ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "jsonAta": "JsonAta ಸ್ಪೆಕ್",
  "jsonAtaPlaceholder": "JsonAta ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "encodedJsonAtaSpec": "ಎನ್ಕೋಡ್ ಮಾಡಿದ JsonAta ಸ್ಪೆಕ್",
  "encodedJsonAtaSpecPlaceholder": "ಎನ್ಕೋಡ್ ಮಾಡಿದ JsonAta ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",

  "joltAppTitle": "ಜೋಲ್ಟ್ ಸ್ಪೆಕ್ ನಿರ್ವಹಣೆ",
  "createSpec": "ಸ್ಪೆಕ್ ರಚಿಸಿ",
  "encode": "ಎನ್‌ಕೋಡ್",
  "decode": "ಡಿಕೋಡ್",
  "spec": "ಸ್ಪೆಕ್",
  "decodeXsltSpec": "ಡಿಕೋಡ್ ��ಾಡಿದ XSLT ವಿವರಣೆ",
  "decodeJsonAtaSpec": "ಡಿಕೋಡ್ ಮಾಡಿದ JsonAta ವಿವರಣೆ",

  "entityType": "ಘಟಕದ ಪ್ರಕಾರ",
  "eventIntervalSeconds": "ಘಟನೆಯ ಅಂತರ ಸೆಕೆಂಡುಗಳು",
  "cronExpression": "ಕ್ರೋನ್ ಅ��ಿವ್ಯಕ್ತಿ",
  "entityName": "ಘಟಕದ ಹೆಸರು",

  "edit": "ಸಂಪಾದಿಸು",
  "runJob": "ಕೆಲಸ ಚಲಾಯಿಸು",
  "stopScheduler": "ನಿಯೋಜಕವನ್ನು ನಿಲ್ಲಿಸು",
  "machineStatusChange": "ಯಂತ್ರ ಸ್ಥಿತಿ ಬದಲಾವಣೆ",

  "apiToProcess": "ಪ್ರಕ್ರಿಯೆಗೆ API",
  "selectPreProcessJolt": "ಪೂರ್ವ ಪ್ರಕ್ರಿಯೆ ಜೋಲ್ಟ್ ಆಯ್ಕೆಮಾಡಿ",
  "selectPostProcessJolt": "ಪೋಸ್ಟ್ ಪ್ರಕ್ರಿಯೆ ಜೋಲ್ಟ್ ಆಯ್ಕೆಮಾಡಿ",
  "selectPreProcessXSLT": "ಪೂರ್ವ ಪ್ರಕ್ರಿಯೆ XSLT ಆಯ್ಕೆಮಾಡಿ",
  "processJoltXslt": "ಜೋಲ್ಟ್ XSLT ಪ್ರಕ್ರಿಯೆ",
  "splitConfigurations": "ವಿಭಜನೆ ಕಾನ್ಫಿಗರೆಷನ್",
  "splitIdentifier": "ವಿಭಜನೆ ಗುರುತಿಸುವಿಕೆ",
  "conditional": "ಷರತ್ತುಬದ್ಧ",
  "parallel": "ಸಮಾನಾಂತರ",
  "anyOrder": "ಯಾವುದೇ ಕ್ರಮ",

  "orderNumber": "ಆದೇಶ ಸಂಖ್ಯೆ",
  "recipeVersion": "ವಿನ್ಯಾಸ ಆವೃತ್ತಿ",
  "recipeNo": "ವಿನ್ಯಾಸ ಸಂಖ್ಯೆ",
  "targetQuantity": "ಗುರಿ ಪ್ರಮಾಣ",
  "startDate": "ಪ್ರಾರಂಭ ದಿನಾಂಕ",
  "finishDate": "ಅಂತಿಮ ದಿನಾಂಕ",
  "schedFinTime": "ನಿಗದಿತ ಅಂತಿಮ ಸಮಯ",
  "schedStartTime": "ನಿಗದಿತ ಪ್ರಾರಂಭ ಸಮಯ",
  "selectRecipeNo": "ವಿನ್ಯಾಸ ಸಂಖ್ಯೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "batchNumber": "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ",
  "batchNumberQuantity": "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ ಪ್ರಮಾಣ",

  // ============================================== Process Order Plugin ===========================================
  "complete": "ಪೂರ್ಣ",
  "start": "ಪ್ರಾರಂಭಿಸಿ",

  // ============================================== NC Group ===========================================
  "ncGroup": "ನಿಕ್ಷಿಪ್ತ ಸಮೂಹ",
  "ncCode": "ಎನ್‌ಸಿ ಕೋಡ್",
  "ncGroups": "ನಿಕ್ಷಿಪ್ತ ಸಮೂಹಗಳು",
  "ncGroupAppTitle": "ನಿಕ್ಷಿಪ್ತ ಸಮೂಹ ನಿರ್ವಹಣೆ",
  "ncGroupFilterPriority": "ನಿಕ್ಷಿಪ್ತ ಸಮೂಹ ಫಿಲ್ಟರ್ ಪ್ರಾಥಮಿಕೆ",
  "validAtAllOperations": "ಎಲ್ಲಾ ಕಾರ್ಯಗಳಲ್ಲಿ ವಾಸ್ತವವಾಗಿರುತ್ತದೆ",
  // New additions
  "parameterBo": "ಪ್ಯಾರಾಮೀಟರ್ ಬಿಒ",
  "operationBO": "ಕಾರ್ಯಾಚರಣೆ ಬಿಒ",
  "dcGroupBO": "ಡಿಸಿ ಗುಂಪು ಬಿಒ",
  "pcuBO": "ಪಿಸಿಯು ಬಿಒ",
  "testDateTime": "ಪರೀಕ್ಷೆ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "dcGroupDescription": "ಡಿಸಿ ಗುಂಪು ವಿವರಣೆ",
  "subStepID": "ಉಪ ಹಂತ ಐಡಿ",
  "measureStatus": "ಅಳತೆ ಸ್ಥಿತಿ",
  "measureType": "ಅಳತೆ ಪ್ರಕಾರ",
  "unitOfMeasure": "ಅಳತೆಯ ಏಕಕ",
  "highLimit": "ಉನ್ನತ ಮಿತಿ",
  "lowLimit": "ಕಡಿಮೆ ಮಿತಿ",
  "expected": "ನಿರೀಕ್ಷಿತ",
  "actualNum": "ವಾಸ್ತವಿಕ ಸಂಖ್ಯೆ",
  "dcComment": "ಡಿಸಿ ಕಾಮೆಂಟ್",
  "usedLimitSeq": "ಬಳಸಿದ ಮಿತಿ ಕ್ರಮ",
  "elapsedTime": "ಕಳೆದ ಸಮಯ",
  "originalActual": "ಮೂಲ ವಾಸ್ತವಿಕ",
  "originalDcComment": "ಮೂಲ ಡಿಸಿ ಕಾಮೆಂಟ್",
  "originalTestDateTime": "ಮೂಲ ಪರೀಕ್ಷೆ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "edited": "ಸಂಪಾದಿಸಲಾಗಿದೆ",
  "editedUserBO": "ಸಂಪಾದಿಸಿದ ಬಳಕೆದಾರ ಬಿಒ",
  "editedDateTime": "ಸಂಪಾದಿಸಿದ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "internalMeasureID": "ಆಂತರಿಕ ಅಳತೆ ಐಡಿ",
  "routingBO": "ರೌಟಿಂಗ್ ಬಿಒ",
  "stepID": "ಹಂತ ಐಡಿ",
  "userBO": "ಬಳಕೆದಾರ ಬಿಒ",
  "overrideUserBO": "ಓವರ್‌ರೈಡ್ ಬಳಕೆದಾರ ಬಿಒ",
  "dcGroupVersion": "ಡಿಸಿ ಗುಂಪು ಆವೃತ್ತಿ",
  "erpSent": "ಇಆರ್‌ಪಿ ಕಳುಹಿಸಲಾಗಿದೆ",
  "qmAccepted": "QM ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
  "ncCodeDPMOCategory": "ಎನ್‌ಸಿ ಕೆಡ್ ಡಿಪಿಎಂಒ ಶ್ರೆಂಚ",
  "operationList": "ಕಾರ್ಯಾಚರಣೆ ಪಟ್ಟಿ",
  "createNCGroup": "ಎನ್‌ಸಿ ಸಮೂಹ ರಚಿಸಿ",
  "availableNCCodes": "ಉಪಲಬ್ಧ ಎನ್‌ಸಿ ಕೆಡ್",
  "assignNCCodes": "ಎನ್‌ಸಿ ಕೆಡ್ ಸೌಂಪಿಸಿ",
  "ncGroupDeleteMessage": "ನೀವು ಈ ಎನ್‌ಸಿ ಸಮೂಹವನ್ನು ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ?",
  "assignedNC": "ಅಸ್ಥಾಯಿಸಿದ ಎನ್‌ಸಿ",
  "availableNC": "ಉಪಲಬ್ಧ ಎನ್‌ಸಿ",
  "logNc": "ಲೋಗ್ ಏನ್‌ಸಿ",
  "done": "ಪೂರ್ಣ",
  "NcCodeMaintenance": "ಎನ್‌ಸಿ ಕೋಡ್ ನಿರ್ವಹಣೆ",
  "NC Code": "ಎನ್‌ಸಿ ಕೋಡ್",
  "operationGroups": "ಆಪರೇಷನ್ ಗುಂಪುಗಳು",
  "dispositionRoutings": "ವ್ಯವಸ್ಥಿತ ಮಾರ್ಗಗಳು",
  "NC Groups": "ಎನ್‌ಸಿ ಗುಂಪುಗಳು",
  "secondaries": "ದ್ವಿತೀಯಗಳು",
  "createNcCode": "ಎನ್‌ಸಿ ಕೋಡ್ ರಚಿಸಿ",
  "assignNCtoComponent": "ಕಾಂಪೋನೆಂಟ್‌ಗೆ ಎನ್‌ಸಿ ಅಸೈನ್ ಮಾಡಿ",
  "ncCategory": "ಎನ್‌ಸಿ ವರ್ಗ",
  "dpmoCategory": "ಡಿಪಿಎಂಒ ವರ್ಗ",
  "ncDatatype": "ಎನ್‌ಸಿ ಡೇಟಾ ಪ್ರಕಾರ",
  "collectRequiredNCDataonNC": "ಎನ್‌ಸಿಯಲ್ಲಿ ಅಗತ್ಯವಿರುವ ಡೇಟಾವನ್ನು ಸಂಗ್ರಹಿಸಿ",
  "ncPriority": "ಎನ್‌ಸಿ ಪ್ರಾಮುಖ್ಯತೆ",
  "maximumNCLimit": "ಗರಿಷ್ಠ ಎನ್‌ಸಿ ಮಿತಿ",
  "ncSeverity": "ಎನ್‌ಸಿ ತೀವ್ರತೆ",
  "secondaryCodeSpecialInstruction": "ದ್ವಿತೀಯ ಕೋಡ್ ವಿಶೇಷ ಸೂಚನೆ",
  "canBePrimaryCode": "ಪ್ರಾಥಮಿಕ ಕೋಡ್ ಆಗಬಹುದು",
  "closureRequired": "ಮುಚ್ಚುವಿಕೆ ಅಗತ್ಯವಿದೆ",
  "autoClosePrimaryNC": "ಪ್ರಾಥಮಿಕ ಎನ್‌ಸಿಯನ್ನು ಸ್ವಯಂ ಮುಚ್ಚಿ",
  "autoCloseIncident": "ಸ್ವಯಂ ಮುಚ್ಚುವ ಘಟನೆ",
  "secondaryRequiredForClosure": "ಮುಚ್ಚುವಿಕೆಗೆ ದ್ವಿತೀಯ ಅಗತ್ಯವಿದೆ",
  "erpQNCode": "ERP QN ಕೋಡ್",
  "erpCatalog": "ERP ಕ್ಯಾಟಲಾಗ್",
  "erpCodeGroup": "ERP ಕೋಡ್ ಗುಂಪು",
  "erpCode": "ERP ಕೋಡ್",
  "oeeQualityKPIRelevant": "OEE ಗುಣಮಟ್ಟ KPI ಸಂಬಂಧಿತ",
  "selectNcDatatype": "ಎನ್‌ಸಿ ಡೇಟಾ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "validOperations": "ಮಾನ್ಯವಾದ ಕಾರ್ಯಾಚರಣೆಗಳು",
  "dispositionGroups": "ಸ್ಥಿತಿಗತಿ ಗುಂಪುಗಳು",
  "availableRouting": "ಲಭ್ಯವಿರುವ ಮಾರ್ಗ ನಿರ್ವಾಹಕರು",
  "assignedRouting": "ನಿಯೋಜಿತ ಮಾರ್ಗ ನಿರ್ವಾಹಕರು",
  "availableSecondaries": "ಲಭ್ಯವಿರುವ ದ್ವಿತೀಯಗಳು",
  "assignedSecondaries": "ನಿಯೋಜಿತ ದ್ವಿತೀಯಗಳು",
  "availableNcGroups": "ಉಪಲಬ್ಧ ಎನ್‌ಸಿ ಗುಂಪುಗಳು",
  "assignedNcGroups": "ಅಸ್ಥಾಯಿಸಿದ ಎನ್‌ಸಿ ಗುಂಪುಗಳು",
  "copyNcCode": "ಎನ್‌ಸಿ ಕೋಡ್ ಕಳೆಯಿರಿ",
  "toolNumberMaintenance": "ಟೂಲ್ ನಂಬರ್ ನಿರ್ವಹಣೆ",
  "toolNumber": "ಟೂಲ್ ನಂಬರ್",
  "toolGroup": "ಟೂಲ್ ಗುಂಪು",
  "qtyAvailable": "ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣ",
  "erpPlanMaintenanceOrder": "ಇಆರ್‌ಪಿ ಯೋಜನೆ ನಿರ್ವಹಣೆ ಆರ್ಡರ್",
  "toolQty": "ಟೂಲ್ ಪ್ರಮಾಣ",
  "createToolNumber": "ಟೂಲ್ ನಂಬರ್ ರಚಿಸಿ",
  "calibration": "ಕ್ಯಾಲಿಬ್ರೇಷನ್",
  "measurementPoints": "ಮಾಪನ ಪಾಯಿಂಟ್‌ಗಳು",
  "measurementPoint": "ಮಾಪನ ಪಾಯಿಂಟ್",
  "calibrationType": "ಕ್ಯಾಲಿಬ್ರೇಷನ್ ಪ್ರಕಾರ",
  "calibrationPeriod": "ಕ್ಯಾಲಿಬ್ರೇಷನ್ ಅವಧಿ",
  "calibrationCount": "ಕ್ಯಾಲಿಬ್ರೇಷನ್ ಸಂಖ್ಯೆ",
  "maximumCalibrationCount": "ಗರಿಷ್ಟ ಕ್ಯಾಲಿಬ್ರೇಷನ್ ಸಂಖ್ಯೆ",
  "expirationDate": "ಅವಧಿ ಮೀರಿದ ದಿನಾಂಕ",
  "displayClosedNc": "ಬಂದ ಏನ್ಸಿ ಪ್ರದರ್ಶಿಸಿ",
  "selectRoute": "ರೌಟಿಂಗ್ ಆಯ್ಕೆಮಾಡಿ",
  "customOrder": "ಕಸ್ಟಮ್ ಆದೇಶ",
  "createToolGroup": "ಸಾಧನ ಗುಂಪು ರಚಿಸಿ",
  "timeBased": "ಸಮಯ ಆಧಾರಿತ",
  "quantityRequired": "ಅಗತ್ಯವಿರುವ ಪ್ರಮಾಣ",
  "erpGroup": "ERP ಗುಂಪು",
  "itemVersion": "ಐಟಂ ಆವೃತ್ತಿ",
  "trackingControl": "ಟ್ರ್ಯಾಕಿಂಗ್ ಕನ್ಟ್ರೋಲ್",
  "toolGroupMaintenance": "ಸಾಧನ ಗುಂಪು ನಿರ್ವಹಣೆ",
  "listConfiguration": "ಪಟ್ಟಿ ಅಮಾವೃತ್ತಿ",
  "multiProcessOrderRelease": "ಏಕಾಧಿಕ ಪ್ರಕ್ರಿಯೆ ಆದೇಶ ಉತ್ಸರ್ಗ",
  "multiProcessOrder": "ಏಕಾಧಿಕ ಪ್ರಕ್ರಿಯೆ ಆದೇಶ",
  "phase": "ಹಂತಗಳು",
  "mrpController": "ಮ್ರ್ಪ್ ನಿಯಂತ್ರಕ",
  "productionScheduler": "ಉತ್ಪಾದನ ಶೇಡ್ಯೂಲರ್",
  "reservationNumber": "ರಿಜರ್ವೇಶನ್ ಸಂಖ್ಯೆ",
  "productionStartDate": "ಉತ್ಪಾದನ ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "productionFinishDate": "ಉತ್ಪಾದನ ಅಂತಿಮ ದಿನಾಂಕ",
  "actualStartDate": "ವಾಸ್ತವಿಕ ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "actualFinishDate": "ವಾಸ್ತವಿಕ ಅಂತಿಮ ದಿನಾಂಕ",
  "inUse": "ಬಳಸಲಾಗಿದೆ",
  "measuredUom": "ಅಳತೆ ಏಕಕ",
  "entryPhase": "ಪ್ರವೇಶ ಹಂತ",
  "exitPhase": "ನಿಷ್ಕ್ರಿಯ ಹಂತ",
  "entryOperation": "ಪ್ರವೇಶ ಕಾರ್ಯ",
  "lastOperationAtPhase": "ಕಳೆದ ಕಾರ್ಯ",
  "nextPhase": "ಮುಂದಿನ ಹಂತ",

  "accept": "ಸ್ವೀಕರಿಸಿ",
  "partial": "ಆಂಶಿಕ",
  "skip": "ನಿರ್ಗಮಿಸಿ",
  "buyOff": "ಕುರಿಯಾಗಿಸಿ",
  "username": "ಬಳಕೆದಾರ ಹೆಸರು",
  "userAuthentication": "ಬಳಕೆದಾರ ಪ್ರಮಾಣೀಯನ್ನು ಪರಿಶೀಲಿಸಿ",
  "login": "ಪ್ರವೇಶ",
  // ======================================= Certification Maintenance ===========================================
  "certificationmaintenance": "ಪ್ರಮಾಣೀಕರಣ ನಿರ್ವಹಣೆ",
  "certifications": "ಪ್ರಮಾಣಪತ್ರಗಳು",
  "createCertification": "ಪ್ರಮಾಣಪತ್ರ ರಚಿಸಿ",
  "durationType": "ಅವಧಿ ಪ್ರಕಾರ",
  "maxNumberOfExtensions": "ಗರಿಷ್ಠ ವಿಸ್ತರಣೆಗಳ ಸಂಖ್ಯೆ",
  "maxExtensionDuration": "ಗರಿಷ್ಠ ವಿಸ್ತರಣೆ ಅವಧಿ",
  "assignment": "ನಿಯೋಜನೆ",
  "availableUserGroups": "ಲಭ್ಯವಿರುವ ಬಳಕೆದಾರ ಗುಂಪುಗಳು",
  "assignedUserGroups": "ನಿಯೋಜಿತ ಬಳಕೆದಾರ ಗುಂಪುಗಳು",
  "measurementpoints": "ಅಳತೆ ಪಾಯಿಂಟ್‌ಗಳು",
  "copyCertification": "ಪ್ರಮಾಣಪತ್ರ ಕಳೆಯಿರಿ",
  "activityId": "ಚಟುವಟಿಕೆ ಐಡಿ",
  "selectPcu": "ಪ್ರಮಾಣಪತ್ರ ಕಳೆಯಿರಿ",
  "selectBatchNo": "ಬೆಚ್ಚೆ ಸಂಖ್ಯೆ ಆಯ್ಕೆಮಾಡಿ",
  "createPodMaintenance": "ಪ್ರಮಾಣಪತ್ರ ರಚಿಸಿ",
  "reloadWorkList": "ಕಾರ್ಯ ಪಟ್ಟಿ ಮರೆಯಿರಿ",
  "reloadResource": "ಸಂಸ್ಥಾನ ಮರೆಯಿರಿ",
  "settings": "ಸೆಟಿಂಗ್ಸ್",
  "layout": "ಲೇಆಉಟ್",
  "PCUOrBatchNumberBrowseActivity": "PCU ಅಥವಾ ಬೆಚ್ಚೆ ಸಂಖ್ಯೆ ಬ್ರಾಉಜ್ ಚಟುವಟಿಕೆ", 
  "PodWorkListActivity": "ಪ್ರಮಾಣಪತ್ರ ಕಾರ್ಯ ಪಟ್ಟಿ ಚಟುವಟಿಕೆ",
  "ButtonActivityInWork": "ಕಾರ್ಯ ಚಟುವಟಿಕೆ",
  "ButtonActivityInQueue": "ಕ್ರಮ ಚಟುವಟಿಕೆ",
  "OnTabOutOfOperation": "ಕಾರ್ಯ ಸ್ಥಳದಲ್ಲಿ ಬಾಹ್ಯಾಸ್ಥಿತಿ",
  "OnTabOutOfWorkcenter": "ವರ್ಕ್‌ಸೆಂಟರ್ ಸ್ಥಳದಲ್ಲಿ ಬಾಹ್ಯಾಸ್ಥಿತಿ",
  "OnTabOutOfResource": "ಸಂಸ್ಥಾನ ಸ್ಥಳದಲ್ಲಿ ಬಾಹ್ಯಾಸ್ಥಿತಿ",
  "UpdateFieldsToSession": "ಸಮಯದಲ್ಲಿ ಕ್ಷೇತ್ರಗಳನ್ನು ಅಪ್ಡೇಟ್ ಮಾಡಿ",
  "scrapQuantity": "ಸ್ಕ್ರೇಪ್ ಪ್ರಮಾಣ",
  "subPod": "ಉಪ ಪ್ರಮಾಣಪತ್ರ",
  "podCategory": "ಪ್ರಮಾಣಪತ್ರ ಶ್ರೆಂಚ",
  "buttonActivityInQueue": "ಕ್ರಮ ಚಟುವಟಿಕೆ",
  "buttonActivityInWork": "ಕಾರ್ಯ ಚಟುವಟಿಕೆ",
  "activityDescription": "ಗತಿವಿಧಿ ವಿವರಣೆ",
  "panel": "ಪ್ಯಾನೆಲ್",
  "defaultPlugin": "ಡಿಫಾಲ್ಟ್ ಪ್ಲಗಿನ್",
  "otherPlugin": "ಇತರ ಪ್ಲಗಿನ್",
    // ============================================== Line Clearance ===========================================
  "lineClearanceMaintenance": "ಲೈನ್ ಕ್ಲಿಯರೆನ್ಸ್ ನಿರ್ವಹಣೆ",
  "lineClearance": "ಲೈನ್ ಕ್ಲಿಯರೆನ್ಸ್",
  "templateName": "ಟೆಂಪ್ಲೇಟ್ ಹೆಸರು",
  "clearanceTimeLimit": "ಕ್ಲಿಯರೆನ್ಸ್ ಸಮಯ ಮಿತಿ",
  "maxPendingTasks": "ಗರಿಷ್ಠ ಬಾಕಿ ಕಾರ್ಯಗಳು",
  "clearanceReminderInterval": "ಕ್ಲಿಯರೆನ್ಸ್ ರಿಮೈಂಡರ್ ಅಂತರ",
  "notifyOnCompletion": "ಪೂರ್ಣಗೊಂಡಾಗ ಸೂಚಿಸಿ",
  "enablePhotoEvidence": "ಫೋಟೋ ಸಾಕ್ಷ್ಯ ಸಕ್ರಿಯಗೊಳಿಸಿ",
  "associated": "ಸಂಬಂಧಿತ",
  "workcenterId": "ವರ್ಕ್‌ಸೆಂಟರ್ ಐಡಿ",
  "resourceName": "ಸಂಪನ್ಮೂಲ ಹೆಸರು",
  "createLineClearance": "ಲೈನ್ ಕ್ಲಿಯರೆನ್ಸ್ ರಚಿಸಿ",
  "taskid": "ಕಾರ್ಯ ಐಡಿ",
  "taskname": "ಕಾರ್ಯ ಹೆಸರು",
  "mandatory": "ಕಡ್ಡಾಯ",
  "evidencerequired": "ಸಾಕ್ಷ್ಯ ಅಗತ್ಯವಿದೆ",
  "userRoles": "ಬಳಕೆದಾರ ಪಾತ್ರಗಳು",
  "userid": "ಬಳಕೆದಾರ ಐಡಿ",
  "permissions": "ಅನುಮತಿಗಳು",
  "selectUser": "ಬಳಕೆದಾರರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "tasks": "ಕಾರ್ಯಗಳು",
  "uomConversion": "ಯೂಓಎಂ ರೂಪಾಂತರಣೆ",
  "conversion": "ರೂಪಾಂತರಣೆ",
  "materialCountConversion": "Material Count Conversion",
  "convertUom": "ಯೂಓಎಂ ರೂಪಾಂತರಣೆ",
  "count": "ಗಿನತಿ",
  "conversionDeleteMessage": "ಈ ರೂಪಾಂತರಣೆಯನ್ನು ಅಳಿಸಬೇಕೋ?",
  "baseAmt": "ಆಧಾರ ರಾಶಿ",
  "conversionItem": "ರೂಪಾಂತರಣೆ ಆಇಟಂ",
  "areYouSureDeleteThisSplit": "ಈ ವಿಭಾಜನೆಯನ್ನು ಅಳಿಸಬೇಕೋ?",
  "attach": "ಸೇರಿಸಿ",
  "filePreview": "ಫೋಟೋ ಪೂರ್ವಾವಲೋಕನ",
  "change": "ಬದಲಾಯಿಸಿ",
  "preview": "ಪೂರ್ವಾವಲೋಕನ",
  "reloadSiteConfirmation": "ಈ ಸೈಟ್ ಅಳಿಸಲು ಖಚಿತವಾಗಿಯೇ ಇರುವುದೋ?",
  "phaseCanBeChanged": "ಚರಣ ಬದಲಾಯಿಸಬಹುದು",
  "showResource": "ಸಂಸ್ಥಾನ ದಿಕ್ಕೆ",
  "showOperation": "ಕಾರ್ಯ ದಿಕ್ಕೆ",
  "showPhase": "ಚರಣ ದಿಕ್ಕೆ",
  "auditLogReport": "಑ಡಿಟ್ ಲೋಗ್ ರಿಪೋರ್ಟ್",
  "dataCollectionReport": "ಡೇಟಾ ಕಲೆಕ್ಷನ್ ರಿಪೋರ್ಟ್",
  "dataCollectionGraph": "ಡೇಟಾ ಕಲೆಕ್ಷನ್ ಗ್ರಾಫ್",
  "selectCategory": "ಶ್ರೆಂಚ ಆಯ್ಕೆಮಾಡಿ",
  "currentSetting": "ಪ್ರಸ್ತುತ ಸೆಟಿಂಗ್",
  "date/time": "ದಿನಾಂಕ/ಸಮಯ",
  "changeType": "ಪರಿವರ್ತನ ಪ್ರಕಾರ",
  "dateRange": "ದಿನಾಂಕ ವ್ಯಾಪ್ತಿ",
  "time": "ಸಮಯ",
  "topicConfiguration": "ಟೋಪಿಕ್ ಕೊನ್ಫಿಗರೇಶನ್",
  "createTopicConfiguration": "ಟೋಪಿಕ್ ಕೊನ್ಫಿಗರೇಶನ್ ರಚಿಸಿ",
  "topicName": "ಟೋಪಿಕ್ ಹೆಸರು",
  "apiUrl": "ಏಪಿಐ ಯುಆರ್ಲ್",

  "taskDescription": "ಕಾರ್ಯ ವಿವರಣೆ",
  "evidence": "ಪ್ರಮಾಣ",
  "startedDateTime": "ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "completedDateTime": "ಪೂರ್ಣಗೊಂಡಾಗ ದಿನಾಂಕ",
  "reason": "ಕಾರಣ",
  "approved": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
  "approvedDateTime": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "approvedBy": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "rejectedDateTime": "ರದ್ದುಪಡೆದಾಗ ದಿನಾಂಕ",
  "rejectedBy": "ರದ್ದುಪಡೆದಾಗ ದಿನಾಂಕ",
  "updatedDateTime": "ಅಪ್ಡೇಟ್ ದಿನಾಂಕ",
  "updatedBy": "ಅಪ್ಡೇಟ್ ದಿನಾಂಕ",
  "startedBy": "ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "completedBy": "ಪೂರ್ಣಗೊಂಡಾಗ ದಿನಾಂಕ",
  "taskName": "ಕಾರ್ಯ ಹೆಸರು",
  "isMandatory": "ಅನಿವಾರ್ಯ",
  "evidenceRequired": "ಪ್ರಮಾಣ ಅಗತ್ಯ",
  "theme": "ಥೈಮ್",
  "cycleTime(sec)": "ಕಾಲಕ್ರಮ ಸಮಯ (ಸೆಕೆಂಡ್)",

  "shiftStart": "ಶಿಫ್ಟ್ ಪ್ರಾರಂಭ",
  "shiftEnd": "ಶಿಫ್ಟ್ ಅಂತಿಮ",
  "shiftAvailableTime": "ಶಿಫ್ಟ್ ಉಪಲಬ್ಧ ಸಮಯ",
  "totalBreakHours": "ಮೊತ್ತ ಬ್ರೇಕ್ ಘಂಟೆಗಳು",
  "createdDatetime": "ರಚಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "updatedDatetime": "ಅಪ್ಡೇಟ್ ದಿನಾಂಕ",
  "createdBy": "ರಚಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "eventData": "ಘಟನೆ ಡೇಟಾ",
  "plant": "ಫುಲಾವಾ",
  "eventType": "ಘಟನೆ ಪ್ರಕಾರ",
  "buyOffAction": "ಖರೀದಿ ಅವಧಿ ಕ್ರಿಯೆ",
  "history": "ಇತಿಹಾಸ",
  "endDate": "ಅಂತಿಮ ದಿನಾಂಕ",
  "selectSite": "ಸೈಟ್ ಆಯ್ಕೆಮಾಡಿ",
  "downtimeType": "ಡೌನ್ಟೈಮ್ ಪ್ರಕಾರ",
  "selectStatus": "ಸ್ಥಿತಿ ಆಯ್ಕೆಮಾಡಿ",
  "selectNewStatus": "ಹೊಸ ಸ್ಥಿತಿ ಆಯ್ಕೆಮಾಡಿ",
  "selectBatchNumber": "ಬೆಚ್ಚೆ ಸಂಖ್ಯೆ ಆಯ್ಕೆಮಾಡಿ",
  "selectOrderNumber": "ಆದೇಶ ಸಂಖ್ಯೆ ಆಯ್ಕೆಮಾಡಿ",
  "batchStepStatus": "ಬೆಚ್ಚೆ ಸ್ಟೆಪ್ ಸ್ಟ್ಯಾಚ್ ಸ್ಟ್ಯಾಚ್",
  "batchStartedTime": "ಬೆಚ್ಚೆ ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "batchCompletedTime": "ಬೆಚ್ಚೆ ಪೂರ್ಣಗೊಂಡಾಗ ದಿನಾಂಕ",
  "approval": "ಅನುಮೋದನೆ",
  "PhaseId": "ಚರಣ ಐಡಿ",
  "InQueueQty": "ಕ್ರಮ ಮಾತ್ರ",
  "InWorkQty": "ಕಾರ್ಯ ಮಾತ್ರ",
  "CompleteQty": "ಪೂರ್ಣಗೊಂಡ ಮಾತ್ರ", 
  "ScrapQty": "ಸ್ಕ್ರೇಪ್ ಮಾತ್ರ",
  "level": "ಸ್ತರ",
  "message": "ಸಂದೇಶ",

  "activityHookId": "ಚಟುವಟಿಕೆ ಹುಕ್ ಐಡಿ",
  "targetClass": "ಗುರಿ ವರ್ಗ",
  "targetMethod": "ಗುರಿ ವಿಧಾನ",
  "hookType": "ಹುಕ್ ಪ್ರಕಾರ",
  "hookClass": "ಹುಕ್ ವರ್ಗ",
  "hookMethod": "ಹುಕ್ ವಿಧಾನ",
  "executionMode": "ಕಾರ್ಯಗತ ಮೋಡ್",
  "logo": "ಲೋಗೋ",
  "background": "ಬ್ಯಾಕಗ್ರಾಉಂಡ್",
  "color": "ರಂಗ",
  "lineColor": "ವರಿ ರಂಗ",

  "plannedCycleTime": "ಯೋಜನಾ ಕಾಲಕ್ರಮ ಸಮಯ",
  "actualCycleTime": "ವಾಸ್ತವಿಕ ಕಾಲಕ್ರಮ ಸಮಯ",
  "totalBreakInMinutes": "ಮೊತ್ತ ಬ್ರೇಕ್ (ನಿಮಿಷ)",


  "serviceExtension": "ಸೇವಾ ವಿಸ್ತರಣೆ",
  "createServiceExtension": "ಸೇವಾ ವಿಸ್ತರಣೆ ರಚಿಸಿ",
  "createExtension": "ವಿಸ್ತರಣೆ ರಚಿಸಿ",
  "serviceExtensionAppTitle": "ಸೇವಾ ವಿಸ್ತರಣೆ ರಚಿಸಿ",
  "selectResourceType": "ಸಂಸ್ಥಾನ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "executionPointId": "ಕಾರ್ಯಗತ ಬಿಂದು ಐಡಿ",
  "extensionDeleteMessage": "ಈ ವಿಸ್ತರಣೆಯನ್ನು ಅಳಿಸಲು ನೀವು ಬಯಸುವಿರಾ?",
  "executionPoint": "ಕಾರ್ಯಗತ ಬಿಂದು",
  "extensionActivity": "ವಿಸ್ತರಣಾ ಚಟುವಟಿಕೆ",
  "MaterialDescription": "ಮಾಲ್ ವಿವರಣೆ",
  "releaseTime": "ಉತ್ಸರ್ಹ ಸಮಯ",
  "unitOfMeasurement": "ಯೂಓಎಂ",
  "releaseOrder": "ಏಕಾಧಿಕ ಆದೇಶ",
  "createdDateTime": "ರಚಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "releaseQty": "ಉತ್ಸರ್ಹ ಮಾತ್ರ",
  "productionTime": "ಉತ್ಪಾದನ ಸಮಯ",
  "productName": "ಉತ್ಪನ್ನದ ಹೆಸರು",
  "downloadDate": "ಡೌನ್‌ಲೋಡ್ ದಿನಾಂಕ",
  "batchStatus": "ಬೆಚ್ಚೆ ಸ್ಥಿತಿ",


  "createConfiguration": "ಕಾನ್ಫಿಗರೇಷನ್ ರಚಿಸಿ",
  "apiConfiguration": "ಎಪಿಐ ಕಾನ್ಫಿಗರೇಷನ್",
  "storedProcedure": "ಸ್ಟೋರ್ಡ್ ಪ್ರೊಸೀಜರ್",
  "httpMethod": "ಎಚ್ಟಿಟಿಪಿ ವಿಧಾನ",
  "inputParameters": "ಇನ್ಪುಟ್ ಪಾರಾಮೀಟರ್ಸ್",
  "outputStructure": "ಔಟ್ಪುಟ್ ಸ್ಟ್ರಕ್ಚರ್",
  "apiName": "ಎಪಿಐ ಹೆಸರು",
  "deleteApiConfigMessage": "ಈ ಕಾನ್ಫಿಗರೇಷನ್ ಅನ್ನು ಅಳಿಸಲು ನೀವು ಬಯಸುವಿರಾ?",
  "apiConfigMaintenance": "ಎಪಿಐ ಕಾನ್ಫಿಗರೇಷನ್ ನಿರ್ವಹಣೆ",
  "configuration": "ಕಾನ್ಫಿಗರೇಷನ್",

  "shiftId": "ಶಿಫ್ಟ್ ಐಡಿ",
  "selectShift": "ಶಿಫ್ಟ್ ಆಯ್ಕೆಮಾಡಿ",

  "productGroup":"ಉತ್ಪಾದ ಸಮೂಹ",
  "selectProductGroup":"ಉತ್ಪಾದ ಸಮೂಹ ಆಯ್ಕೆಮಾಡಿ",


  "componentBuilderMaintenance": "ಕಂಪೋನೆಂಟ್ ಬಿಲ್ಡರ್ ನಿರ್ವಹಣೆ",
  "validation": "ಪರಿಶೀಲನೆ",
  "defaultValue": "ಡಿಫಾಲ್ಟ್ ಮೌಲ್ಯ",
  "componentLabel": "ಕಂಪೋನೆಂಟ್ ಲೇಬಲ್",
  "createComponent": "ಕಂಪೋನೆಂಟ್ ರಚಿಸಿ",
  "dropdownOptions": "ಡ್ರಾಪ್ಡೌನ್ ಆಯ್ಕೆಗಳು",
  "addOption": "ಆಯ್ಕೆ ಸೇರಿಸಿ",
  "noOfColumns": "ಸ್ತಂಭಗಳ ಸಂಖ್ಯೆ",
  "noOfRows": "ಸಾಲುಗಳ ಸಂಖ್ಯೆ",
  "resourceDetails": "ಸಂಸ್ಥಾನ ವಿವರಣೆ",
}